# Notes 

Run with

jupyter notebook

then load from web browser.

Ensure round is not used as a variable name, I have converted all occurences to ROUND.

Eventually want to generalise for all major penants at CDTTA probably excepting Monday night.

# Wednesday/Thursday nights:

- 7 game matches, first to 11 but with lead of 2 points.
- 10 round
- 2 person teams
- Multiple sections (often 6 composed of 4/6 team sections).
- Missed nights due to holidays
- 4 team sections might have a finals night rather than a bye.

# Monday/Thursday mornings:

- 3 game matches, first to 21 but with a lead of 2 points.
- 10 rounds
- 2 person teams
- Multiple sections (often 4 composed of 4/6 team sections).
- Missed nights due to holidays
- 4 team sections might have a bye rather than a finals night.

# Todo/Reminders

- find various place(s) where matches are checked. 
- - remove [11, 11, 0, 0, 11] V [

In [2]:
print('BEGIN')

CRED = '\033[91m'
CGREEN = '\033[32m'
CBLUE = '\033[34m'
CCYAN = '\033[36m'
CEND = '\033[0m'

import numpy as np

from datetime import date
from datetime import timedelta
import datetime
import inspect
import itertools
import sys
#import psutil
import pandas as pd
import ipywidgets as widgets
from ipywidgets import Layout, interact, interact_manual, HBox, VBox
from IPython.display import display
from IPython.core.display import display, HTML
import json
import IPython
import os
import glob
import shutil

#from IPython.display import HTML

# from cdtta import \
#     sort_matches_list_of_tuples, \
#     tuple_pair_to_list, \
#     find_first_new, \
#     check_match, \
#     compare_single_match, \
#     pad_score, populate_scores, \
#     process_single_match, \
#     plot_sheet

__file__='jupyter_notebook' #this can be deleted when written to a python script and loaded as module.

print('END')

BEGIN
END

In [3]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

# DATA (NEED TO BE LOADED)

In [4]:
print('BEGIN')

Wednesday_Night_Player_Ranking = [ \
'Taylor, Ben', \
'Gin, Darian', \
'Ghani, Shahid', \
'Waterman, Keith', \
'Smith, Jakob', \
'D\â€™Amico, Scott', \
'Menzies, Andrew', \
'Datta, Raj', \
'Nemenyi, Endre', \
'Brindley, Aviva', \
'Gardner, Mackenzie', \
'Rodriguez, JC', \
\
'Paul, Liviston', \
'Majumdar, Sourav', \
'Jones, Warren', \
'Gormann, Ben', \
'Roy, Phillip', \
'Evans, Richard P', \
'Evans, Bruce', \
'Kwan, Justin', \
'Smith, Greg', \
'Cunningham, Bobby', \
'Spizzica, Tony', \
'Hayden, Ryan', \
'Maranan, Jesse', \
'Jefimenko, Walter', \
'Hewitt, Gerard', \
'Qin, Allen', \
\
'Tsao, Justin', \
'Hayes, Simon', \
'Cauchi, Travis', \
'Cheung, Adrian', \
'Simons, Shane', \
'Hayden, Shane', \
'Cung, Robert', \
'Neil, Alan', \
'Khan, Inaaya', \
'Brincat, Tony', \
'Stewart, Craig', \
'Julian, Rebecca', \
\
'Marsden, Bob', \
'Perkins, Shaun', \
'Bignell, Quentin', \
'Jafarzadeh, Jason', \
'Perkins, David', \
'Morella, Alex', \
'Eddy, Chris', \
'McConnell, Nick', \
'Mehravar, Hassan', \
'Evans, Shaun', \
'Chew, Valentine', \
'Woodlock, Ron', \
\
'Menz, Garry', \
'Petch, David', \
'Herweynen, Ed', \
'Brown, Andrew', \
'Hayden, Chris', \
'Jones, Cameron', \
'Hassanikhoo, Hamid', \
'Conroy, Mark', \
'Van Koll, Marinus', \
'Wachter, Matt', \
'Floyd, Dannie', \
'Atalla, Maged', \
\
'Byrne, Jason', \
'Evans, Steve', \
'Shamakhy, Alireza', \
'Cao, Tingting', \
'Gray, Kaitlyn', \
'Anderson, Caleb', \
'Puts, Arnold', \
'Balsillie, Terry', \
\
'Thompson, Nick', \
'Safir, Amir', \
'McGuire, Johnathon', \
'Morales, Orangel', \
'Martus, Maria', \
'Anderson, Daniel', \
'Rowland, David', \
'Chegini, Fereshteh' \
]

f = open('ranking.txt', 'r')
Thursday_Night_Player_Ranking_tmp = f.readlines()
f.close()

Thursday_Night_Player_Ranking = []
for r in Thursday_Night_Player_Ranking_tmp:
    Thursday_Night_Player_Ranking.append(r.rstrip('\n').strip())

#print(Thursday_Night_Player_Ranking)

Monday_Morning_Player_Ranking = [ \
'Lothar Pilz', \
'Pam Tait', \
'John Keating', \
'Steve Aitken', \
'Tony Brincat', \
'ByeS1A', \
'ByeS1B', \
'John Kelly', \
'Brian Zschech', \
'Colin Geraghty', \
'Bob Marsden', \
'Rodney Matthews', \
\
'Ray Butcher', \
'Marcell Asselman', \
'Paul Colcheedas', \
'Neil Roberts', \
'Graeme Ireland', \
'Kevin Packer', \
'Peter Rial', \
'Barney Zwartz', \
'Andrew Bialecki', \
'Clive Hawes', \
'Jim Goodwin', \
'Richard Hince', \
\
'Robert Varsallo', \
'Graham Fly', \
'Robert Priest', \
'Sandra Rowe', \
'Bruce Hird', \
'ByeS3A', \
'ByeS3B', \
'Lyn Gilson', \
'Jimmy McHale', \
'Fumiko Suwama', \
'Arthur Rich', \
'Jim Barden', \
\
'Glen Swatek', \
'Bert Grotaers', \
'Margaret Thomas', \
'Katalin Szabo', \
'Max Edwards', \
'Colin Bateman', \
'Helga Spitzer', \
'Adele Rooke' \
]
    
Thurday_Morning_Player_Ranking = [
'Bob Marsden', \
'Fred Arthurton', \
'Neil Roberts', \
'Graeme Ireland', \
'Barney Zwartz', \
'ByeS1A', \
'ByeS1B', \
'Peter Rial', \
'Sandra Rowe', \
'Louis Markov', \
'Louis Markov', \
'Clive Hawes', \
'Bruce Hird', \
\
'Rob Cameron', \
'Peter Roberts', \
'Jimmy Mchale', \
'Laurie Uglow', \
'Paul Stitzel', \
'ByeS2A', \
'ByeS2B', \
'Graham Woodfield', \
'Hans Gaven', \
'Dylan Thorrogood', \
'Ian Stockdale', \
'Jim Barden', \
\
'Fumiko Suwama', \
'Ruth Menzies', \
'Margaret Thomas', \
'Katalin Szabo', \
'Joe Britton', \
'ByeS3A', \
'ByeS3A', \
'Roselyn Beatty', \
'Marilyn Mcfarland', \
'Dorothy Markly', \
'Max Edwards', \
'Glen Swatek', \
\
'Bob Byran', \
'Colin Bateman', \
'Rhonda Addicott', \
'Pat Searle', \
'Joan Schofield', \
'ByeS4A', \
'ByeS4B', \
'Lily Stevenson', \
'Sue Foster', \
'Ken Merry', \
'Margaret Hopstaken', \
'Helga Spitzer' \
]

Wednesday_Night_Team_Names = [ \
'Mooroolbark Bendigo', \
'Kilsyth Gin', \
'Wonga Park', \
'Ferntree Gully', \
'The Basin', \
'Knox', \
\
'Belgrave', \
'Tooronga Zoo', \
'Montrose Jones', \
'Kilsyth', \
'Bayswater Roy', \
'North Ringwood', \
'Alamein', \
'Mitcham', \
\
'Kilsyth', \
'Croydon', \
'Bayswater', \
'Wantirna', \
'Donvale', \
'Knoxfield', \
\
'Vermont South', \
'Studfield', \
'Tooronga Zoo', \
'Kilsyth', \
'Scoresby', \
'Boronia', \
\
'Forest Hill', \
'North Ringwood', \
'Scoresby', \
'Vermont', \
'Yellingbo', \
'Croydon Hills', \
\
'Vermont', \
'Badger Creek', \
'Blackburn', \
'Box Hill', \
'Scoresby', \
'Kilsyth', \
\
'Coldstream', \
'Wantirna', \
'Heathmont', \
'Forest Hill', \
\
'Ringwood', \
'Lilydale', \
'Kilsyth', \
'Warburton' \
]

Thursday_Night_Team_Names = [ \
'Bandicoot', \
'Bilby', \
'Brolga', \
'Cassowary', \
\
'Cockatoo', \
'Crocodile', \
'Dingo', \
'Dolphin', \
'Dugong', \
'Echidna', \
\
'Emu', \
'Fairy Penguin', \
'Flying Fox', \
'Fur Seal', \
'Galah', \
'Goanna', \
\
'Ibis', \
'Kangaroo', \
'Koala', \
'Kookaburra', \
'Lizard', \
'Lyrebird', \
\
'Magpie', \
'Numbat', \
'Platypus', \
'Possum', \
'Quokka', \
'Quoll', \
\
'Seal', \
'Sugar Glider', \
'Tasmanian Devil', \
'Turtle' \
]

Monday_Morning_Team_Names = [ \
'Bayswater1', \
'Croydon1', \
'Kilsyth1', \
'Lilydale1', \
'Ringwood1', \
'ByeS1', \
\
'Croydon2', \
'Bayswater2', \
'Kilsyth2', \
'Ringwood2', \
'Mooroolbark', \
'Olinda1', \
\
'Ringwood3', \
'Bayswater3', \
'Olinda2', \
'Croydon3', \
'Kilsyth3', \
'ByeS3', \
\
'Olinda3', \
'Bayswater4', \
'Ringwood4', \
'Lilydale2' \
]

Thursday_Morning_Team_Names = [\
'Bayswater1', \
'Croydon1', \
'Kilsyth1', \
'Lilydale1', \
'Ringwood1', \
'ByeS1', \
\
'Croydon2', \
'Bayswater2', \
'Kilsyth2', \
'Ringwood2', \
'Mooroolbark', \
'ByeS2', \
\
'Ringwood3', \
'Bayswater3', \
'Olinda1', \
'Croydon3', \
'Kilsyth3', \
'ByeS3', \
\
'Olinda2', \
'Croydon4', \
'Bayswater4', \
'Lilydale2', \
'Ringwood4' \
'ByeS4' \
]

print('END')

BEGIN
END

# LOCAL FUNCTIONS (NEED TO BE LOADED)

# functions updated in cdtta/src/cdtta_funcs.py and need to be udpated here...

In [5]:
print('BEGIN')

##################################################################################################

diag = True
diag = False

##################################################################################################

def sort_matches_list_of_tuples(diag, matches):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    '''
    aa = ()
    for b in matches:
        c,d = b
        aa += (tuple(sorted([c,d])),)
    sorted_matches = list(set(aa))
    return(sorted_matches) #end of sort_matches_list_of_tuples

################################################################################

def tuple_pair_to_list(diag, values):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    '''
    #print('values=',values)
    #convert to a list
    newlist = []
    for v in values:
        a,b = v
        newlist.append([a,b])
    return(newlist) #end of tuple_pair_to_list

################################################################################

def current_and_remainder(diag, all_items):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    this works by supplying a list _all_items_. It creates a _current_rounds_ list based on first entry and unique teams.
    the remaining matches _all_items_remainder_ are returned for the next iteration.
    in theory it will take an integer number of passes to produce the full set of unique matches.
    these unque matches will then be used to form the total set for the season (10 if no final=4 teams and 9 if a final=6 teams).
    '''
    
    import copy

    all_items_remainder = copy.deepcopy(all_items)
    
    current_rounds = [all_items[0]]

    #print('BEFORE MAIN LOOP:')
    if(diag): print('current_and_remainder: all_items=',all_items)
    if(diag): print('current_and_remainder: current_rounds=',current_rounds)
    if(diag): print('current_and_remainder: all_items_remainder=',all_items_remainder)

    #print('current_rounds[0]=',current_rounds[0])
    
    all_items_remainder.remove(current_rounds[0])
    
    if(diag): print('current_and_remainder: all_items_remainder=',all_items_remainder)        
    ##print('BEFORE MAIN LOOP:')
    
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
    for cnt,item in enumerate(all_items[1::]):
        if(diag): print(CRED+'cnt='+str(cnt)+CEND,'item=',item)

        #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
        cnt_item_current_round = 0
        for current_round in current_rounds:
            
            if(current_round[0] in item or current_round[1] in item):
                cnt_item_current_round += 1
                if(diag): print('match a team, no good')

            else:
                cnt_item_current_round += 0
                if(diag): print('no match team, good')
 
        if(cnt_item_current_round == 0): 
            current_rounds.append(item)
            all_items_remainder.remove(item) #remove match from list if found to be good
            #new_item = False
            
        if(diag): print('current_rounds=',current_rounds)
        if(diag): print('cnt_item_current_round=',cnt_item_current_round)
            
    #print('AFTER MAIN LOOP:')
    if(diag): print('all_items_remainder=',all_items_remainder)
    if(diag): print('current_rounds=',current_rounds)
    #print('AFTER MAIN LOOP:')
    
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    return(current_rounds, all_items_remainder)#end of current_and_remainder

################################################################################

def order_of_play_one_iteration(diag, number_team_this_section):
    import inspect
    
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    '''

    all_matches_one_round = list(itertools.combinations((range(1,number_team_this_section+1)),2))

    if(diag): print('all_matches_one_round=',all_matches_one_round)

    sorted_matches = sort_matches_list_of_tuples(False, all_matches_one_round)

    if(diag): print('sorted_matches=',sorted_matches)

    list_of_matches_now = tuple_pair_to_list(diag, sorted_matches)

    if(diag): print('list_of_matches_now=',list_of_matches_now)

    all_teams_round = []
    
    for ROUND in range(number_team_this_section-1):

        if(diag): print(CGREEN+'ROUND='+str(ROUND)+CEND)

        current_round, remainder = current_and_remainder(diag, list_of_matches_now)

        list_of_matches_now = remainder

        if(diag): print('first_matches_current_round=',first_matches_current_round)

        if(diag): print(CRED+'output: current_round='+CEND,current_round)
        
        if(diag): print(CRED+'output: list_of_matches_now='+CEND,list_of_matches_now)

        #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
        all_teams_round += current_round

    if(len(list_of_matches_now) != 0): raise SystemExit('len(list_of_matches_now) should == 0:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
    return(all_teams_round) #end of order_of_play_one_iteration

################################################################################

def reverse_home_team(diag, datas):
    '''
    datas: 2 dimensional list.
    reversed_datas: 2 dimension list or inner array switched.
    '''
    #print('reverse_home_team: datas=',datas)
    reversed_datas = []
    for data in datas:
        reversed_datas.append( [data[1],data[0]] )
    return(reversed_datas) #end of reverse_home_team

################################################################################

def chunk_them(diag, j, n):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    j is a unique set of matches using all combinations, for a complete season it will need to be utilised several times - and reversed for alternating rounds.
    k will put them into the correct number of matches per round (chunks).
    '''
    k = []
    if(diag): print('j=',j)
    
    x = []
    for m in range(len(j)):
        if(diag): print('m,n,m%n=',m,n,m%n)
        if(m%n == 0):
            x = [ j[m] ]
        elif(m%n == n-1):
            x += [ j[m] ]
            k += [ x ]
            x = []
        else:
            x += [ j[m] ]
            
    if(diag): print('k=',k)

    return(k) #end of chunk_them

################################################################################

def check_match(diag, X, number_of_games_per_match, number_of_matches_per_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    various checks on a single game.
    '''
    #diag=True
    import inspect

#     #think this can be done generally with int(number_of_games_per_match+1/4):
#     if(number_of_games_per_match==7):
#         minimum_values = 4
#     elif(number_of_games_per_match==3):
#         minimum_values = 2
#     else:
#         raise Exception('Exception8') 
    #minimum_values = int((number_of_games_per_match+1)/2) #works for odd number_number_of_games_per_match
    
    minimum_values = minimum_games_in_match(diag, number_of_games_per_match)
    
    if(diag): print(X)
    if(len(X) < minimum_values): raise SystemExit('check_match: len(X) < minimum_values:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    if(len(X) > number_of_games_per_match): raise SystemExit('check_match: len(team X) > number_of_games_per_match:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
    for game0 in range(len(X)):
        if(X[game0] < 0): raise SystemExit('check_match: X[game0] < 0:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        if(X[game0] > 99): print(CRED+'check_match: warning: X[game0] > 99:'+__file__+' line number: '+str(inspect.stack()[0][2])+CEND)

    match_X_points = sum(X)
    match_X_games = len(X)
    
    return(match_X_points, match_X_games) #end of check_match

################################################################################

def compare_single_match(diag, A, B, number_of_games_per_match, number_of_matches_per_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    various checks on a single match.
    Inputs:

    A: list []
    B: list []
    Outputs:

    Ascore,Bscore: lists []

    '''
    #diag=True
    import inspect

    if(len(A) != len(B)): raise SystemExit('compare_single_match: len(A) != len(B):'+__file__+' line number: '+str(inspect.stack()[0][2]))
   
    D = []
    if(diag): print(A,B)
    
    if(diag): print('A=',A)
    if(diag): print('B=',B)
    
    for cnt, a in enumerate(A):
        if(A[cnt]!= 0 & B[cnt]!= 0 & A[cnt] == B[cnt]): \
            raise SystemExit('compare_single_match: A[cnt] == B[cnt]:'+__file__+' line number: '+str(inspect.stack()[0][2]))
   
        D.append(A[cnt]- B[cnt])
    
    #print(A-B)
    if(diag): print('D=',D)
    
    Ascore,Bscore = 0,0
    for d in D:
        if(d>0): Ascore += 1
        if(d<0): Bscore += 1
            
    Extra_points = number_of_games_per_match - (Ascore+Bscore)
    
    if(diag): print('Extra_points=',Extra_points)
    
    if(Extra_points < 0): \
        raise SystemExit('compare_single_match: #Extra_points < 0:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    if(Extra_points > 4): \
        raise SystemExit('compare_single_match: #Extra_points > 4:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
    if(Extra_points > 0):
        if(Ascore > Bscore): Ascore += Extra_points
        elif(Bscore > Ascore): Bscore += Extra_points
            
    return(Ascore,Bscore) #end of compare_single_match

################################################################################

def pad_score(diag, score):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    create 7 entries for a 7 game match.
    '''
    import inspect
    
    if(diag): print('pad_score: score=',score)
    
    if(len(score) < 1): raise SystemExit('pad_score: len(score) <1:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    if(len(score) > 7): raise SystemExit('pad_score: len(score) >7:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    pscore = []
    for p in score:
        if(diag): print('p=',p)
        pscore.append(str(p))
        
    for x in range(7-len(score)):
        pscore.append(' ')

    return(pscore) #end of pad_score

################################################################################

def populate_scores(diag, scores):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    '''
    import inspect
    
    if(diag): print('populate_scores: scores=',scores)
    if(diag): print('populate_scores: len(scores)=',len(scores))
    if(len(scores) != 5): \
        raise SystemExit('populate_scores: len(scores) != 5:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    padded_scores = [] 
    for score in scores:
        if(diag): print('score=',score)

        padded_scores.append([pad_score(diag, score[0]), pad_score(diag, score[1])])
        
    if(diag): print('padded_scores=',padded_scores)
    
    match1_AB = padded_scores[0][0]
    match1_XY = padded_scores[0][1]

    match2_AB = padded_scores[1][0]
    match2_XY = padded_scores[1][1]
    
    match3_AB = padded_scores[2][0]
    match3_XY = padded_scores[2][1]
    
    match4_AB = padded_scores[3][0]
    match4_XY = padded_scores[3][1]
    
    match5_AB = padded_scores[4][0]
    match5_XY = padded_scores[4][1]

    if(diag): print('match1_AB,match1_XY=',match1_AB,match1_XY)
    if(diag): print('match5_AB,match5_XY=',match5_AB,match5_XY)
        
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    return(match1_AB,match2_AB,match3_AB,match4_AB,match5_AB, \
        match1_XY,match2_XY,match3_XY,match4_XY,match5_XY) #end of populate_scores

################################################################################

def process_single_match(diag, A, B, number_of_games_per_match, number_of_matches_per_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    various checks.
    '''

    if(diag): print(A,B)
    
    match_A_points,match_A_games = check_match(diag, A, number_of_games_per_match, number_of_matches_per_match)
    match_B_points,match_B_games = check_match(diag, B, number_of_games_per_match, number_of_matches_per_match)
    
    if(diag): print('match_A_points,match_A_games=',match_A_points,match_A_games)
    if(diag): print('match_B_points,match_B_games=',match_B_points,match_B_games)
    
    Ascore,Bscore = compare_single_match(diag, A, B, number_of_games_per_match, number_of_matches_per_match)
    
    if(diag): print('Ascore,Bscore=',Ascore,Bscore)
    
    return(Ascore,Bscore,match_A_points,match_B_points) #end of process_single_match

################################################################################

def match_5xN(diag, df, N):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    setup for 5 matches, N games each.
    '''
    out_list = []

    teamA = chunk_them(diag, df.sort_values(by=['Unique game'])['Results Team A'].tolist(), N)
    teamB = chunk_them(diag, df.sort_values(by=['Unique game'])['Results Team B'].tolist(), N)

    if(diag): print('teamA=',teamA)
    if(diag): print('teamB=',teamB)

    for n in range(5):
        out_list.append([teamA[n], teamB[n]])
    return(out_list) #end of match_5xN

################################################################################

def check_for_empty(diag, scores_whole_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    There are only two kinds of match scores
    1. empty set
    2. regular set with meaningful numbers.
    '''
    #diag = False
    empty = False
    length = 0
    for x in range(len(scores_whole_match)):
        if(diag): print('x',x,scores_whole_match[x])
        for y in range(len(scores_whole_match[x])):
            #print(y,scores_whole_match[x][y])
            if(diag): print('y',y,len(scores_whole_match[x][y]))
            if(len(scores_whole_match[x][y]) != 0): length += 1
    if(length == 0): empty = True
    return(empty) # end of check_for_empty

################################################################################

def match_team_summary(diag, full_table_df, section, ROUND, match, verbose, number_of_games_per_match, number_of_matches_per_match, override_result):
    '''
    Creator: Mark Collier
    Last Modified: 21 August 2019
    
    Inputs:
    
    section (1-max):
    ROUND (0-max): is capatalised as round is a system defined function.
    match (1-max): every round and section has a unique set of matches.
    override_result: this will override the match results found in full_table_df
        so that we can see them printed in susmmary form, without having to create another function.

    Outputs:
    
    1. team_sheet_df: a single team sheet match (like used/generated on match night)
    2. summary_df: summary of points (like used/generated on match night)
    '''
    import inspect
    import pandas as pd
    from IPython.display import display
    import numpy as np
    CRED = '\033[91m'
    CGREEN = '\033[32m'
    CEND = '\033[0m'
    
    if(number_of_games_per_match == 7):
        maximum_match_points = 41
    elif(number_of_games_per_match == 3):
        maximum_match_points = 21
    else:
        raise SystemExit('maximum_match_points only 41/21.'+__file__+' line number: '+str(inspect.stack()[0][2]))        
        
    #round_df = main_df.loc[main_df['Round'] == ROUND]
    
    #extract_match = full_table_df.query('Round == '+str(ROUND)).query('Section == '+str(section)).query('Match == '+str(match)).values
    
    extract_match = full_table_df.loc[(full_table_df['Round'] == ROUND) & (full_table_df['Section'] == section) & (full_table_df['Match'] == match)]
    
    if(diag): display(extract_match)

    #print('extract_match=',extract_match)
    
    team1_player1 = extract_match['Team1 Player1'].values[0]
    team1_player2 = extract_match['Team1 Player2'].values[0]
    team2_player1 = extract_match['Team2 Player1'].values[0]
    team2_player2 = extract_match['Team2 Player2'].values[0]
    
#     team1_player1 = extract_match[0][7]
#     team1_player2 = extract_match[0][8]
#     team2_player1 = extract_match[0][10]
#     team2_player2 = extract_match[0][11]

    if(diag): print('team1_player1=',team1_player1)
    if(diag): print('team1_player2=',team1_player2)

    if(diag): print('team2_player1=',team2_player1)
    if(diag): print('team2_player2=',team2_player2)

    team1 = extract_match['Team1'].values[0]
    team2 = extract_match['Team2'].values[0]
    
#     team1 = extract_match[0][6]
#     team2 = extract_match[0][9]

    if(diag): print('team1=',team1)
    if(diag): print('team2=',team2)

    scores_whole_match = extract_match['Result'].values[0]
    
    #scores_whole_match = extract_match[0][-1]

    #heiden
    
    if(diag): print('match_team_summary: scores_whole_match=',scores_whole_match)
        
    if(type(override_result) != type(None)):
        print(CRED+'match_team_summary: overriding match result with new values.'+CEND)
        #uncomment later:
        scores_whole_match = override_result
        if(diag): print('match_team_summary: scores_whole_match=',scores_whole_match)

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    if(check_for_empty(diag, scores_whole_match)):
        if(verbose): print(CGREEN+'match_team_summary: scores are empty.'+CEND)
        return(None, None)
        #raise SystemExit('scores are empty:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    if(len(scores_whole_match)!=5): \
            raise SystemExit('#matches not equal 5:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    team1_rubbers,team2_rubbers = 0,0
    team1_games,team2_games = 0,0
    team1_bonus_point,team2_bonus_point = 0,0
    team1_total_points,team2_total_points = 0,0

    team1_scores,team2_scores = 0,0

    team1_rubbers_list,team2_rubbers_list = [],[]
    team1_scores_list,team2_scores_list = [],[]
    for match0 in range(len(scores_whole_match)):
        #print('match0=',match0)

        team1_current_match = scores_whole_match[match0][0]
        team2_current_match = scores_whole_match[match0][1]

        team1_score,team2_score,team1_points,team2_points =  \
            process_single_match(diag, team1_current_match, team2_current_match, number_of_games_per_match, number_of_matches_per_match)

    #     print('team1_score,team2_score=',team1_score,team2_score)
    #     print('team1_points,team2_points=',team1_points,team2_points)

        #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

        team1_scores_list.append(team1_score)
        team2_scores_list.append(team2_score)

        team1_total_points += team1_points
        team2_total_points += team2_points

        if(team1_score > team2_score):
            team1_rubbers +=1
            team1_rubbers_list.append(1)
            team2_rubbers_list.append(0)
        elif(team2_score > team1_score):
            team2_rubbers +=1
            team2_rubbers_list.append(1)
            team1_rubbers_list.append(0)

        else:
            raise SystemExit('issue1:'+__file__+' line number: '+str(inspect.stack()[0][2]))

        team1_scores += team1_score
        team2_scores += team2_score

        #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    if(team1_rubbers > team2_rubbers):
        team1_bonus_point += 1
    elif(team2_rubbers > team1_rubbers):
        team2_bonus_point += 1
    else:
        raise SystemExit('issue2:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    # print('team1_rubbers,team2_rubbers=',team1_rubbers,team2_rubbers)
    # print('team1_bonus_point,team2_bonus_point=',team1_bonus_point,team2_bonus_point)
    # print('team1_total_points,team2_total_points=',team1_total_points,team2_total_points)

    team1_total_score = sum(team1_scores_list) + team1_rubbers + team1_bonus_point
    team2_total_score = sum(team2_scores_list) + team2_rubbers + team2_bonus_point

    #print('team1_total_score,team2_total_score=',team1_total_score,team2_total_score)

    if((team1_total_score + team2_total_score) != maximum_match_points): \
        raise SystemExit('(team1_total_score + team2_total_score) != maximum_match_points:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    if(team1_total_score > team2_total_score):
        print(CRED+'Team A/B wins over Team X/Y.'+CEND)
    elif(team1_total_score < team2_total_score):
        print(CRED+'Team X/Y wins over Team A/B.'+CEND)
    else:
        raise SystemExit('issue3:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    # empty_match = ['11','11','11','11','11']
    # empty_match = [' ',' ',' ',' ',' ']
    # empty_match = [' ',' ',' ',' ',' ']
    # empty_summary = [' ',' ',' ',' ']
    # summary = [' ',' ',' ',' ']

    team1_summary = [sum(team1_scores_list),team1_rubbers,team1_bonus_point,team1_total_score]
    team2_summary = [sum(team2_scores_list),team2_rubbers,team2_bonus_point,team2_total_score]

    # game1_AB = game2_AB = game3_AB = game4_AB = game5_AB = game6_AB = game7_AB = empty_match
    # game1_XY = game2_XY = game3_XY = game4_XY = game5_XY = game6_XY = game7_XY = empty_match

    #print('team1_scores_list,team2_scores_list=',team1_scores_list,team2_scores_list)

    match1_AB,match2_AB,match3_AB,match4_AB,match5_AB, \
    match1_XY,match2_XY,match3_XY,match4_XY,match5_XY, \
    = populate_scores(diag, scores_whole_match)

    #print('match1_AB=',match1_AB)

    match_AB = [match1_AB,match2_AB,match3_AB,match4_AB,match5_AB]
    match_XY = [match1_XY,match2_XY,match3_XY,match4_XY,match5_XY]

    #print('match_AB=',match_AB)

    match_AB_T = np.array(match_AB).T.tolist()
    match_XY_T = np.array(match_XY).T.tolist()

    #print('match_AB_T=',match_AB_T)

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
    if(number_of_games_per_match == 7):
        team_sheet_df = pd.DataFrame({ \
                            'TeamA/B: '+team1 : ['Player1: '+team1_player1, 'Player2: '+team1_player2, 'Player2: '+team1_player2, 'Player1: '+team1_player1, 'Doubles'], \
                            'GAME 1,' : match_AB_T[0], \
                            '2,' : match_AB_T[1], \
                            '3,' : match_AB_T[2], \
                            '4,' : match_AB_T[3], \
                            '5,' : match_AB_T[4], \
                            '6,' : match_AB_T[5], \
                            '7,' : match_AB_T[6], \
                            'TeamX/Y: '+team2: ['Player1: '+team2_player1, 'Player2: '+team2_player2, 'Player1: '+team2_player2, 'Player2: '+team2_player1, 'Doubles'], \
                            'GAME 1' : match_XY_T[0], \
                            '2' : match_XY_T[1], \
                            '3' : match_XY_T[2], \
                            '4' : match_XY_T[3], \
                            '5' : match_XY_T[4], \
                            '6' : match_XY_T[5], \
                            '7' : match_XY_T[6], \
                            'G A/B' : team1_scores_list, \
                            'G X/Y' : team2_scores_list, \
                            'R A/B' : team1_rubbers_list, \
                            'R X/Y' : team2_rubbers_list, \
                          })
    elif(number_of_games_per_match == 3):
        team_sheet_df = pd.DataFrame({ \
                            'TeamA/B: '+team1 : ['Player1: '+team1_player1, 'Player2: '+team1_player2, 'Player2: '+team1_player2, 'Player1: '+team1_player1, 'Doubles'], \
                            'GAME 1,' : match_AB_T[0], \
                            '2,' : match_AB_T[1], \
                            '3,' : match_AB_T[2], \
                            'TeamX/Y: '+team2: ['Player1: '+team2_player1, 'Player2: '+team2_player2, 'Player1: '+team2_player2, 'Player2: '+team2_player1, 'Doubles'], \
                            'GAME 1' : match_XY_T[0], \
                            '2' : match_XY_T[1], \
                            '3' : match_XY_T[2], \
                            'G A/B' : team1_scores_list, \
                            'G X/Y' : team2_scores_list, \
                            'R A/B' : team1_rubbers_list, \
                            'R X/Y' : team2_rubbers_list, \
                          })
    else:
        raise SystemExit('maximum_match_points only 41/21.'+__file__+' line number: '+str(inspect.stack()[0][2]))  

    summary_df = pd.DataFrame({ \
                               'Summary': ['Games', 'Rubbers', 'Bonus Pt', 'Total Pts'], \
                               'A/B': team1_summary, \
                                'X/Y': team2_summary \
                              })

    return(team_sheet_df, summary_df) # end of match_team_summary

################################################################################

def update_team_rank(diag, team_sheet_df, summary_df, number_of_games_per_match, number_of_matches_per_match):
    
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    update team ranking based on team_sheet_df and summary_df dataframes.
    '''
    import pandas as pd
    from IPython.display import display
    
    header = team_sheet_df.keys()

    if(diag): print('header=',header)
    
    if(diag): display(team_sheet_df)
    
    #round_df = main_df.loc[main_df['Round'] == ROUND]

    #need to improve on this, should be able to pull out info. in more general way:
    if(number_of_games_per_match==7):
        teamA =header[0].split(':')[2].strip() #replace(' ', '')
        teamB =header[8].split(':')[2].strip() #replace(' ', '')
    elif(number_of_games_per_match==3):
        teamA =header[0].split(':')[2].strip() #replace(' ', '')
        teamB =header[4].split(':')[2].strip() #replace(' ', '')
    else:
        raise SystemExit('number_of_games_per_match only 3/7 currently:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
    if(diag): print('teamA=',teamA)
    if(diag): print('teamB=',teamB)

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
    teamA_points = summary_df['A/B'].values[-1]
    teamB_points = summary_df['X/Y'].values[-1]

    if(diag): print('teamA_points=',teamA_points)
    if(diag): print('teamB_points=',teamB_points)

    for cnt,team in enumerate((teamA,teamB,)):
        entry = team_rank[team]

        #print('entry=',entry)
        entry[0] += 1

        if(cnt==0):
            entry[1] += teamA_points
            entry[2] += teamB_points
        else:
            entry[1] += teamB_points
            entry[2] += teamA_points

        #print('entry=',entry)
        team_rank[team] = entry

    return(team_rank) #end of update_team_rank

################################################################################

def update_player_rank(diag, team_sheet_df, number_of_games_per_match, number_of_matches_per_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    update player leader board based on team_sheet_df dataframe.
    '''
    import pandas as pd
    
    #need to improve on this, should be able to pull out info. in more general way:
    if(number_of_games_per_match==7):
        teamAB_players_tmp = team_sheet_df.iloc[:,0].values
        teamXY_players_tmp = team_sheet_df.iloc[:,8].values
    elif(number_of_games_per_match==3):
        teamAB_players_tmp = team_sheet_df.iloc[:,0].values
        teamXY_players_tmp = team_sheet_df.iloc[:,4].values
    else:
        raise SystemExit('number_of_games_per_match only 3/7 currently:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
    #teamAB_players_tmp = team_sheet_df.iloc[:,0].values
    #teamXY_players_tmp = team_sheet_df.iloc[:,8].values
    #teamXY_players_tmp = team_sheet_df.iloc[:,4].values
    #print('teamAB_players=',teamAB_players)

    teamAB_players = []
    for player in teamAB_players_tmp[0:-1]:
        teamAB_players.append( player.split(':')[1].strip() )

    teamXY_players = []
    for player in teamXY_players_tmp[0:-1]:
        teamXY_players.append( player.split(':')[1].strip() )

    if(diag): print('teamAB_players=',teamAB_players)
    if(diag): print('teamXY_players=',teamXY_players)

    #need to improve on this, should be able to pull out info. in more general way:
    if(number_of_games_per_match==7):
        teamAB_results = team_sheet_df.iloc[:,16][0:-1].values
        teamXY_results = team_sheet_df.iloc[:,17][0:-1].values
    elif(number_of_games_per_match==3):
        teamAB_results = team_sheet_df.iloc[:,9][0:-1].values
        teamXY_results = team_sheet_df.iloc[:,10][0:-1].values
    else:
        raise SystemExit('number_of_games_per_match only 3/7 currently:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
    if(diag): print('teamAB_results=',teamAB_results)
    if(diag): print('teamXY_results=',teamXY_results)

    if(diag): print('player_rank=',player_rank)

    for cnt,player in enumerate(teamAB_players):
        if(diag): print('player=',player)
        entry = player_rank[player]
        entry[0] = entry[0] + teamAB_results[cnt]
        entry[1] = entry[1] + teamXY_results[cnt]
        entry[2] = entry[2] + teamAB_results[cnt] + teamXY_results[cnt]
        if(diag): print('entry=',entry)
        player_rank[player] = entry

    for cnt,player in enumerate(teamXY_players):
        entry = player_rank[player]
        entry[0] = entry[0] + teamXY_results[cnt]
        entry[1] = entry[1] + teamAB_results[cnt]
        entry[2] = entry[2] + teamXY_results[cnt] + teamAB_results[cnt]
        #print('entry=',entry)
        player_rank[player] = entry

    return(player_rank) #end of update_player_rank

################################################################################

def reset_team_player_rank(diag, section_team_composition_df):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    reset team and player leader board based on section_team_composition_df dataframe.
    '''
    import pandas as pd

    team_rank = {}
    for team in section_team_composition_df['Team Name'].values:
        team_rank[team] = [0,0,0]

    player_rank = {}
    for player in section_team_composition_df['Player 1'].values:
        #print('aaa'+player+'bbb')
        player_rank[player] = [0,0,0]
    for player in section_team_composition_df['Player 2'].values:
        #print('aaa'+player+'bbb')
        player_rank[player] = [0,0,0]
        
    return(team_rank, player_rank) #end of reset_team_player_rank

################################################################################

def print_player_table(diag, player_table):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    print player leader board dataframe.
    '''
    from IPython.display import display
    import pandas as pd

    won,lost,total = [],[],[]
    for player in list(player_table.keys()):
        #print(player_table[player])
        won.append(player_table[player][0])
        lost.append(player_table[player][1])
        total.append(player_table[player][2])
    player_table_df = pd.DataFrame({ \
                                    'Player': list(player_table.keys()), \
                                    'Section': [section0+1] * len(list(player_table.keys())), \
                                    'Won': won, \
                                    'Lost': lost, \
                                    'Total': total, \
                                   })

    display(player_table_df.sort_values(by='Won', ascending=False))
    return() # end of print_player_table

################################################################################

def print_team_table(diag, player_table):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    print team leader board dataframe.
    '''
    from IPython.display import display
    import pandas as pd
    
    rounds,won,lost = [],[],[]
    for team in list(team_table.keys()):
        #print(team_table[team])
        rounds.append(team_table[team][0])
        won.append(team_table[team][1])
        lost.append(team_table[team][2])
    team_table_df = pd.DataFrame({ \
                                    'Team': list(team_table.keys()), \
                                    'Section': [section0+1] * len(list(team_table.keys())), \
                                    'Rounds': rounds, \
                                    'Won': won, \
                                    'Lost': lost, \
                                   })

    display(team_table_df.sort_values(by='Won', ascending=False))
    return() # end of print_player_table

################################################################################

def string_list_to_integer_list(diag, list_string):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    '''
    list_integer = []
    for cnt in range(len(list_string)):
        try:
            list_integer.append( int(list_string[cnt]))
        except:
            return()
        
    return(list_integer) #end of string_list_to_integer_list

################################################################################

def keyboard_entry(diag, entry, number_of_games_per_match, number_of_matches_per_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019
    
    Take keyboard entry, will return exception if entry does not follow expected conventions.
    Inputs:
    entry:
    
    Outputs:
    list of integers padded and length 2 e.g. [[11,11,11,11,0,0,0], [9,9,9,9,9,0,0]]
    '''
    
    #think this can be done generally with int(number_of_games_per_matchmonth+1/4):
#     if(number_of_games_per_match==7):
#         minimum_values = 4
#     elif(number_of_games_per_match==3):
#         minimum_values = 2
#     else:
#         raise Exception('Exception8')

    minimum_values = minimum_games_in_match(diag, number_of_games_per_match)

    j = entry.split(':')
    k1 = string_list_to_integer_list(diag, j[0].split(','))
    k2 = string_list_to_integer_list(diag, j[1].split(','))    

    if(diag): print('k1=',k1)
    if(diag): print('k2=',k2)
        
    if(len(k1) != len(k2)):
        print('keyboard_entry: len(k1) != len(k2).')
        raise Exception('Exception1')

    for cnt in range(len(k1)):
        if(k1[cnt] < 11 and k2[cnt] < 11):
            print('k1[cnt] < 11 and k2[cnt] < 11.')
            raise Exception('Exception4')

    for cnt in range(len(k1)):
        if(k1[cnt] == k2[cnt]):
            print('k1[cnt] == k2[cnt].')
            raise Exception('Exception7')
            
    for cnt in range(len(k1)):
        if(k1[cnt] > k2[cnt]):
            if(k1[cnt] - k2[cnt] < 2):
                print('k1[cnt] > k2[cnt] & k1[cnt] - k2[cnt] < 2.')
                raise Exception('Exception5')
        if(k2[cnt] > k1[cnt]):
            if(k2[cnt] - k1[cnt] < 2):
                print('k2[cnt] > k1[cnt] & k2[cnt] - k1[cnt] < 2.')
                raise Exception('Exception6')
                
        #print(cnt, k1[cnt]-k2[cnt])
        #return(None)
        #raise SystemExit('keyboard_entry: len(k1) != len(k2):'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
    if((len(k1) < minimum_values) or (len(k2) < minimum_values )):
        print('keyboard_entry: (len(k1) < minimum_values) or (len(k2) < minimum_values ).')
        raise Exception('Exception2')
        #raise SystemExit('keyboard_entry: (len(k1) < minimum_values) or (len(k2) < minimum_values ):'+__file__+' line number: '+str(inspect.stack()[0][2]))

    if((len(k1) > number_of_games_per_match) or (len(k2) > number_of_games_per_match )):
        print('keyboard_entry: (len(k1) > number_of_games_per_match) or (len(k2) > number_of_games_per_match ).')
        raise Exception('Exception3')
        #raise SystemExit('keyboard_entry: (len(k1) > number_of_games_per_match) or (len(k2) > number_of_games_per_match ):'+__file__+' line number: '+str(inspect.stack()[0][2]))
   
    if(len(k1) < number_of_games_per_match):
        k1_old = k1
        for k in range(number_of_games_per_match-len(k1_old)):
            k1 += [0]

    if(len(k2) < number_of_games_per_match):
        k2_old = k2
        for k in range(number_of_games_per_match-len(k2_old)):
            k2 += [0]
            
    if(diag): print(k1)
    if(diag): print(k2)

    return([k1] + [k2]) #end of keyboard_entry

################################################################################

def live_match(diag, main_df, number_of_games_per_match, number_of_matches_per_match, output_directory, json_orient):
    '''
    Creator: Mark Collier
    Last Modified: 21 August 2019
    
    This is run on match night to capture results into json file, it loops continuously.
    
    Will need to modify to add other features to json files, for example:
    1. date of creation
    2. user name
    3. flag whether been checked by coordinator
    
    Might need to move validated files to another area, and provide protection for the files.
    
    Inputs:
    the main data frame, currently called full_table_df
    
    Outputs:
    
    json text file of convention, e.g., cdtta_json/section_01_round_01_match_01.json
    '''
    
    import datetime
    import pandas as pd
    from IPython.display import display
    import os.path
    import string
    
    CRED = '\033[91m'
    CGREEN = '\033[32m'
    CEND = '\033[0m'
    
    print('Entering a 0 (zero) at first character for any of the following keyboard entry will reset to beginning.')
    print('Only a file will be written if each section is answered appropriately.')
    
    rounds = main_df['Round']
    sections = main_df['Section']
    
    for n in range(99):
        try:
            PERSON_ENTERING_DATA = input('Enter your full name (person entering match results) - alpha & spaces allowed: ')
        except:
            print('Try again.')
            continue
            
        if(PERSON_ENTERING_DATA == ''):
            print('No blanks, try again.')
            continue
        elif(not PERSON_ENTERING_DATA.replace(' ', '').isalpha()):
            print('Only alphabet letters,  again.')
            continue
        else:
            break
    
    TODAYS_DATE_TIME = datetime.datetime.now()
    
    print('PERSON ENTERING DATA='+PERSON_ENTERING_DATA+' DATE/TIME (YYYY-MM-DD HH:MM:SS)=', TODAYS_DATE_TIME)

    for n in range(99):
        try:
            ROUND = int(input('Round '+str(min(rounds))+'-'+str(max(rounds))+': '))
        except ValueError:
            print('Incorrect type, try again.')
            continue
        if(ROUND == 0): return(1)
        
        if(ROUND < min(rounds) or ROUND > max(rounds)):
            continue
        else:
           break

    round_df = main_df.loc[main_df['Round'] == ROUND]

    display(round_df)

    for n in range(99):
        try:
            section = int(input('Section '+str(min(sections))+'-'+str(max(sections))+': '))
        except ValueError:
            print('Incorrect type, try again.')
            continue
        if(section == 0): return(1)
        if(section < min(sections) or section > max(sections)):
            continue
        else:
           break

    section_df = round_df.loc[round_df['Section'] == section]

    display(section_df)

    matches = section_df['Match']

    for n in range(99):
        try:
            match = int(input('Match '+str(min(matches))+'-'+str(max(matches))+': '))
        except ValueError:
            print('Incorrect type, try again.')
            continue
        if(match == 0): return(1)
        if(match < min(matches) or match > max(matches)):
            continue
        else:
           break

    match_extract_df = section_df.loc[round_df['Match'] == match]

    display(match_extract_df)

    #output_directory = 'cdtta_json'
    #keep data and meta (scalar) data in separate files...
    
    output_data_file = 'section_'+'{0:02d}'.format(section)+'_round_'+'{0:02d}'.format(ROUND)+'_match_'+'{0:02d}'.format(match)+'_data.json'
    output_meta_file = 'section_'+'{0:02d}'.format(section)+'_round_'+'{0:02d}'.format(ROUND)+'_match_'+'{0:02d}'.format(match)+'_meta.json'
    
    if(os.path.isfile(output_directory+'/'+output_data_file)):
        print(CRED+'Warning: output file '+output_directory+'/'+output_data_file+ ' exists.'+CEND)
    else:
        print(CGREEN+'Output file=',output_directory+'/'+output_data_file+CEND)

    if(os.path.isfile(output_directory+'/'+output_meta_file)):
        print(CRED+'Warning: output file '+output_directory+'/'+output_meta_file+ ' exists.'+CEND)
    else:
        print(CGREEN+'Output file=',output_directory+'/'+output_meta_file+CEND)
        
    # def padded_integer_match(diag, keyboard_entry):
    #     '''
    #     '''
    #     j = keyboard_entry.split(':')
    #     #print('j=',j)
    #     k1 = string_list_to_integer_list(diag, j[0].split(','))
    #     k2 = string_list_to_integer_list(diag, j[1].split(','))

    #     return([k1] + [k1]) #end of padded_integer_match
    # j = match1.split(':')
    # if(len(j) != 2):
    #     print('j wrong length')

    team1_player1 = match_extract_df['Team1 Player1'].values.tolist()[0].strip()
    team1_player2 = match_extract_df['Team1 Player2'].values.tolist()[0].strip()

    team2_player1 = match_extract_df['Team2 Player1'].values.tolist()[0].strip()
    team2_player2 = match_extract_df['Team2 Player2'].values.tolist()[0].strip()

    team1 = match_extract_df['Team1'].values.tolist()[0].strip().split(':')[1]
    team2 = match_extract_df['Team2'].values.tolist()[0].strip().split(':')[1]

    #print(team1)
    #print(team1_player1)

    print('Note Team 1/2 are home/away teams. So order would be:')
    print('Singles: Team 1 player 1 VS. Team 2 player 1')
    print('Singles: Team 1 player 2 VS. Team 2 player 2')
    print('Singles: Team 1 player 2 VS. Team 2 player 1')
    print('Singles: Team 1 player 1 VS. Team 2 player 2')
    print('Doubles: Team 1 VS. team 2')

    print('Enter scores (comma & colon separated) in order from printed match sheet:')

    print('Example 7 game format: PlayerA VS. PlayerB = 11,3,11,13,11 : 9,11,9,11,9')
    print('Example 3 game format: PlayerA VS. PlayerB = 21,21 : 19,19')

    print('7 game format: Must have minimum of 4 integers even if they are 0, e.g. 0,0,0,0 : 11,11,11,11')
    print('3 game format: Must have minimum of 2 integers even if they are 0, e.g. 0,0 : 21,21')

    # dummy1 = '11,3,11,13,11 : 9,11,9,11,9'
    # dummy2 = '11,11,11,11 : 9,9,9,9'
    # dummy3 = '9,9,9,9 : 11,11,11,11'
    # dummy4 = '11,9,11,9,11,9,11 : 9,11,9,11,9,11,9'
    # dummy5 = '19,11,11,9,11 : 17,9,9,11,9'

    for n in range(99):
        dummy1 = input('Singles Match 1/5: ')
        if(dummy1 == '0'): return(1)
        try:
            match1_join = keyboard_entry(diag, dummy1, number_of_games_per_match, number_of_matches_per_match)
            break
        except:
            print('Try again.')
            continue

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    for n in range(99):
        dummy2 = input('Singles Match 2/5: ')
        if(dummy2 == '0'): return(1)

        try:
            match2_join = keyboard_entry(diag, dummy2, number_of_games_per_match, number_of_matches_per_match)
            break
        except:
            print('Try again.')
            continue

    for n in range(99):
        dummy3 = input('Singles Match 3/5: ')
        if(dummy3 == '0'): return(1)

        try:
            match3_join = keyboard_entry(diag, dummy3, number_of_games_per_match, number_of_matches_per_match)
            break
        except:
            print('Try again.')
            continue

    for n in range(99):
        dummy4 = input('Singles Match 4/5: ')
        if(dummy4 == '0'): return(1)

        try:
            match4_join = keyboard_entry(diag, dummy4, number_of_games_per_match, number_of_matches_per_match)
            break
        except:
            print('Try again.')
            continue

    for n in range(99):
        dummy5 = input('Doubles Match 5/5: ')
        if(dummy5 == '0'): return(1)
        try:
            match5_join = keyboard_entry(diag, dummy5, number_of_games_per_match, number_of_matches_per_match)
            break
        except:
            print('Try again.')
            continue

    #print('match1_join=',match1_join)
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    # match1_join = keyboard_entry(diag, dummy1)
    # match2_join = keyboard_entry(diag, dummy2)
    # match3_join = keyboard_entry(diag, dummy3)
    # match4_join = keyboard_entry(diag, dummy4)
    # match5_join = keyboard_entry(diag, dummy5)

    teamA = match1_join[0] + match2_join[0] + match3_join[0] + match4_join[0] + match5_join[0]
    teamB = match1_join[1] + match2_join[1] + match3_join[1] + match4_join[1] + match5_join[1]

    # print(teamA)
    # print(teamB)
    #print('k2=',k2)
    #print('xxx=',xxx)
    #print( pad_score(diag, k1) )
    # _,_ = check_match(diag, k1)
    # _,_ = check_match(diag, k2)
    # _,_ = compare_single_match(diag, k1, k2)
    # raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))


    # teamA = [9,11,9,11,9,11,9, 9,11,9,11,9,11,9, 9,11,9,11,9,11,9, 9,11,9,11,9,11,9, 9,11,9,11,9,11,9]
    # teamB = [11,9,11,9,11,9,11, 11,9,11,9,11,9,11, 11,9,11,9,11,9,11, 11,9,11,9,11,9,11, 11,9,11,9,11,9,11]
    
#     games = [1,2,3,4,5,6,7] * 5 # a repeating sequence.

    games = list(range(1,number_of_games_per_match+1)) * number_of_matches_per_match
    
    data_df = pd.DataFrame({ \
                                'Unique game': range(1,len(games)+1), \
                                'Section' : [section] * len(games), \
                                'Round' : [ROUND] * len(games), \
                                'Match' : [match] * len(games), \
                                'Games': games, \
                                'Results Team A' : teamA, \
                                'Results Team B' : teamB, \
#                                 'Entry Person' : [PERSON_ENTERING_DATA] * len(games), \
#                                 'Date/Time Creation': [TODAYS_DATE_TIME] * len(games),\
                      })
    
    meta_df = pd.DataFrame([{ \
                                'Entry Person': PERSON_ENTERING_DATA, \
                                'Date/Time Creation': TODAYS_DATE_TIME}])

    display(data_df)
    display(meta_df)
    
    print('Writing to json file: '+output_directory+'/'+output_data_file)
    print('Writing to json file: '+output_directory+'/'+output_meta_file)
    
    data_df.to_json(r''+output_directory+'/'+output_data_file, orient=json_orient)
    
    tidy_json(diag, r''+output_directory+'/'+output_data_file)
    
    meta_df.to_json(r''+output_directory+'/'+output_meta_file, orient=json_orient)
    
    # j_df = pd.read_json(r''+output_directory+'/'+output_file, orient=json_orient)

    # display(j_df)
    return(0) # end of live_match

################################################################################

def minimum_games_in_match(diag, number_of_games_per_match):
    '''
    Creator: Mark Collier
    Last Modified: 16 August 2019   
    
    Inputs:
    number_of_games_per match: (integer)
    Ouputs: (integer), the minimum number of games to be played to finish a match, depends on odd/even number of total games.
    number: 
    '''
    
    if((number_of_games_per_match % 2) == 0): #even
        number = int(number_of_games_per_match/2)+1
    else:
        number = int((number_of_games_per_match+1)/2)
    
    return(number) #end of minimum_games_in_match

################################################################################

def make_draw(diag, all_sections_all_rounds, YYYYMMDD):
    '''
    Creator: Mark Collier
    Last Modified: 19 August 2019
    
    Create a draw (dates, matches in order, per round)
    
    Inputs:
    all_sections_all_rounds: list [[[[ ]]]]
    YYYYMMDD: list of dates corresponding to each round

    Ouputs: list of dataframes: these can be dsiplayed
    '''
    import pandas as pd
    from IPython.display import display
    
    draw_all_df = []
    
    if(diag): print(YYYYMMDD)

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))        

    if(diag): print('all_sections_all_rounds=',all_sections_all_rounds)

    #########################

    unique_draws = [ all_sections_all_rounds[0].copy() ]

    if(diag): print('unique_draws=',unique_draws)

    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))        

    for cnt,one_section in enumerate(all_sections_all_rounds[1:]):
        if(one_section in unique_draws):
            continue
        else:
            unique_draws += [ one_section ]

    if(diag): print('unique_draws=',unique_draws)
    if(diag): print('len(unique_draws)=',len(unique_draws))

    if(diag): print('all_sections_all_rounds=',all_sections_all_rounds)
    if(diag): print('len(all_sections_all_rounds)=',len(all_sections_all_rounds))

    #########################

    sections_common = [[]] * len(unique_draws)

    if(diag): print('sections_common=',sections_common)

    for cntA,one_draw in enumerate(unique_draws):
        for cntB,one_section in enumerate(all_sections_all_rounds):

            if(one_section == unique_draws[cntA]):
                sections_common[cntA] = sections_common[cntA] + [cntB,]

    if(diag): print('sections_common=',sections_common)

    #########################

    printTEXT = True #will print out to screen summary.
    printTEXT = False
       
    for cntA,section_common in enumerate(sections_common):
        if(printTEXT): print('Sections ', end='')
        for cntB,sss in enumerate(section_common):
            if(cntB == len(section_common)-1):
                if(printTEXT): print(sss+1, end=':\n')

            else:
                if(printTEXT): print(sss+1, end=',')
        for cntC,matches_this_round in enumerate(all_sections_all_rounds[section_common[0]]):
            if(printTEXT): print('round,date,matches=',cntC+1,YYYYMMDD[cntC],matches_this_round)

        one_df = pd.DataFrame({'Round': range(1,len(all_sections_all_rounds[section_common[0]])+1), \
                           'Date' : YYYYMMDD, \
                           'Matches': all_sections_all_rounds[section_common[0]], \
                          })
        
        draw_all_df.append(one_df)
        
        #display(one_df)
    return(draw_all_df) #end make_draw

################################################################################

def tidy_json(diag, input_output_file):
    '''
    Creator: Mark Collier
    Last Modified: 19 August 2019
    
    Minor changes to make the json file more readable.
    
    Inputs:
    input file

    Outputs:
    output_file
    '''
    import inspect
    
    ifh = open(input_output_file)
    for i,line in enumerate(ifh):
        line = line.replace(',{"Unique',',\n{"Unique')
        if(diag): print(line)
    ifh.close()
    
    if(diag): print('i=',i)
        
    if(i!=0):
        raise SystemExit('tidy_json: i.ne.0:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    ofh = open(input_output_file, 'w')
    print(line,file=ofh)
    ofh.close()
    
    return() #end of tidy_json

################################################################################

def reduce_size_to_section_size(diag, tables, tables_per_section):
    '''
    Creator: Mark Collier
    Last Modified: 20 August 2019
    
    Inputs:
    tables
    tables_per_section

    Outputs:
    reduced: a reduced version of tables matching tables_per_section
    '''
    
    if(diag): print('tables=',tables)
    
    reduced = []
    for cnt,tables_this_section in enumerate(tables_per_section):
        if(diag): print('cnt,tables_this_section,tables[cnt]=',cnt,tables_this_section,tables[cnt][0:tables_this_section])
        reduced.append(tables[cnt][0:tables_this_section])
    
    return(reduced) #end of reduce_size_to_section_size

################################################################################

def generate_tables_per_section(diag, number_teams_per_section):
    '''
    Creator: Mark Collier
    Last Modified: 20 August 2019
    
    Inputs:
    number_teams_per_section e.g. [4, 6, 6, 6, 6, 4]
    tables_per_section

    Outputs:
    tables per section e.g. [2, 3, 3, 3, 3, 2]
    '''
    
    tables_per_section = []
    for teams in number_teams_per_section:
        tables_per_section.append(int(teams/2))
    return(tables_per_section) #end of generate_tables_per_section

################################################################################

def automatic_table_allocation(diag, number_teams_per_section, number_rounds, groups_of_n, table_max, table_init):
    '''
    Creator: Mark Collier
    Last Modified: 20 August 2019
    
    Inputs:
    number_teams_per_section e.g. [4, 6, 6, 6, 6, 4]
    number_rounds e.g. 10
    groups_of_n e.g. 3, this number is the largest section size
    table_max e.g. 22, this is the largest table number that can be used
    table_init e.g. 11, this is the first table to start to use, 11 corresponds to the first table in the new room.

    Outputs:
    list of [[[ section, round ]]]
    
    Note that at the moment this function will always give a result, however, it can become erroneous in
    situations where the number of sections and teams per section become too great, as the number of tables is
    the limiting factor.
    
    For this reason, I will add code to ensure that unique table numbers are derived, else an error will be reported.
    '''
    
    import inspect
    
    tables_per_section = generate_tables_per_section(diag, number_teams_per_section)
    
    tables_basic_round = []
    for section0 in range(len(number_teams_per_section)):

        if(diag): print('section0,table_init=',section0,table_init)

        table_section = []
        for table in range(groups_of_n):
            table_now = table_init + table

            if(table_now > table_max):
                table_now = table_now - table_max

            table_section.append(table_now)

        if(diag): print('before: table_section=',table_section)

        icheck = 0
        for n in range(groups_of_n-1):
            if(table_section[n] > table_section[n+1]):
                print('table_section[n] > table_section[n+11]')
                icheck +=1

        if(diag): print('icheck=',icheck)

        if(icheck!=0):
            imin = min(table_section)
            if(diag): print('imin=',imin)

            for n in range(gropus_of_n):
                table_section[n] = imin+n
            table_init = imin + gropus_of_n
        else:
            table_init += groups_of_n

        if(table_init > table_max):
            table_init = table_init - table_max

        if(diag): print('after: table_section=',table_section)

        tables_basic_round.append(table_section)

    if(diag): print('tables_basic_round=',tables_basic_round)

    n_rounds = tables_basic_round *12 #choose some big number probably nrounds+1 or nrounds+2

    #print('n_rounds=',n_rounds)

    all_rounds_table_allocation = []

    smin0 = 0
    smax0 = number_sections-1
    for round0 in range(number_rounds):

        if(round0>0):
            smin0 += number_sections-1
            smax0 += number_sections-1

        #print('round0,n_rounds[smin0:smax0+1]=',round0,n_rounds[smin0:smax0+1])

        current_round_table_allocation = reduce_size_to_section_size(diag, n_rounds[smin0:smax0+1], tables_per_section)

        xycheck = []
        for x in current_round_table_allocation:
            for y in x:
                xycheck.append(y)
            

        if(len(xycheck) != len(list(set(xycheck)))):
            print('current_round_table_allocation=',current_round_table_allocation)
            print('xycheck=',xycheck)
            raise SystemExit('automatic_table_allocation: dupliate tables, reduce sections and/or section sizes:'+__file__+' line number: '+str(inspect.stack()[0][2]))
            
        all_rounds_table_allocation.append(current_round_table_allocation)
        if(diag): print('round0,current_round_table_allocation=',CRED+str(round0)+CEND,current_round_table_allocation)

    if(diag): print('all_rounds_table_allocation=',all_rounds_table_allocation)
    
    #reorder array to be as required:
    all_sections_all_rounds_tables = []
    for section0 in range(number_sections): 
        j = []
        for round0 in range(number_rounds):
            j.append( all_rounds_table_allocation[round0][section0] )
        all_sections_all_rounds_tables.append(j)

    if(diag): print('all_sections_all_rounds_tables=',all_sections_all_rounds_tables)

    return(all_sections_all_rounds_tables) # end of automatic_table_allocation

################################################################################

def just_file_name(diag, full_name):
    '''
    
    Extract file name from end of a directory/filename path.
    
    Creator: Mark Collier
    Last Modified: 21 August 2019
    
    Inputs:

    Outputs:
    '''
    file_name = full_name.split('/')[-1]
    return(file_name) #end of just_file_name

################################################################################

def section_ROUND_match_from_json_file(diag, file_name):
    '''
    Creator: Mark Collier
    Last Modified: 21 August 2019
    
    Extract match integers from a match json input file.
    
    Inputs:

    Outputs:
    '''
    input_json_file = just_file_name(diag, file_name)
    if(diag): print('section_ROUND_match_from_json_file: input_json_file=', input_json_file)

    tokens = input_json_file.split('_')
    if(diag): print(tokens)

    section = int(tokens[1])
    ROUND = int(tokens[3])
    match = int(tokens[5])
    
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
    return(section, ROUND, match) #end of section_ROUND_match_from_json_file

################################################################################

print('END')

BEGIN
END

# Basic data

In [6]:
print('BEGIN')

# Pennant = "Wednesday Night"
Pennant = "Thursday Night"
# Pennant = "Monday Morning"
# Pennant = "Thursday Morning"

override_draw = False #force order of matches to be that given online/printed. Future seasons will use my ordering.
override_table = False

#json_status = 0 #ignore files in main_draw_df creation.
#json_status = 1 #read only validated files
#json_status = 2 #read only raw files
json_status = 3 #read both validated and raw files

if(not json_status in [0,1,2,3]):
    raise SystemExit('function: json_status invalid.'+__file__+' line number: '+str(inspect.stack()[0][2]))

if(Pennant=="Wednesday Night"):
    Unique_Team_Names = Wednesday_Night_Team_Names
    Unique_Player_Ranking = Wednesday_Night_Player_Ranking
    holiday_nomatches = [None]
    first_round = datetime.date(2019,7,18)
    number_of_games_per_match = 7
    number_of_matches_per_match = 5

elif(Pennant=="Thursday Night"):
    Unique_Team_Names = Thursday_Night_Team_Names
    Unique_Player_Ranking = Thursday_Night_Player_Ranking
    json_directory = 'cdtta_thursday_night_json' #where json database files are kept.
    holiday_nomatches = [datetime.date(2019,8,1), datetime.date(2019,8,8)]
    holiday_nomatches = [None]
    first_round = datetime.date(2019,7,18)
    number_of_games_per_match = 7
    number_of_matches_per_match = 5
    override_draw = True #force order of matches to be that given online/printed. Future seasons will use my ordering.
    override_table = True #force table allocation to be that given online/printed. Future seasons will use my ordering.
    #override_table = False
    
elif(Pennant=="Monday Morning"):
    Unique_Team_Names = Monday_Morning_Team_Names
    Unique_Player_Ranking = Monday_Morning_Player_Ranking
    json_directory = 'cdtta_monday_morning_json' #where json database files are kept.
    holiday_nomatches = [None]
    first_round = datetime.date(2019,7,18)
    number_of_games_per_match = 3
    number_of_matches_per_match = 5
    
    #here, for the 4 team section, there are only 9 rounds, so one day is a holiday (e.g. 2nd week)
    #bye's are played out accordingly.
    
elif(Pennant=="Thursday Morning"):
    Unique_Team_Names = Thursday_Morning_Team_Names
    Unique_Player_Ranking = Thursday_Morning_Player_Ranking
    json_directory = 'cdtta_thursday_morning_json' #where json database files are kept.
    holiday_nomatches = [None]
    first_round = datetime.date(2019,7,18)
    number_of_games_per_match = 3
    number_of_matches_per_match = 5
    
else:
    raise SystemExit('Pennant, '+Pennant+'Does not exist:'+__file__+' line number: '+str(inspect.stack()[0][2]))
#Unique_Team_Names = Wednesday_Night_Team_Names

number_rounds = 10

number_of_players = len(Unique_Player_Ranking)

number_players_per_team = 2

number_teams = int(number_of_players / number_players_per_team)

#print('number_teams=',number_teams)

number_teams_float = (number_of_players / number_players_per_team)

#print('number_teams_float=',number_teams_float)

if(number_teams_float-number_teams!=0.0):
    raise SystemExit('function: number of players not divisible by 2 for 2 person team:'+__file__+' line number: '+str(inspect.stack()[0][2]))

validated_json_directory = json_directory+'/'+'validated'

if(not os.path.exists(json_directory)):
    raise SystemExit('function: json_directory doesnt exist.'+__file__+' line number: '+str(inspect.stack()[0][2]))

if(not os.path.exists(validated_json_directory)):
    raise SystemExit('function: validated_json_directory doesnt exist.'+__file__+' line number: '+str(inspect.stack()[0][2]))

json_orient = 'split'
json_orient = 'records'

print('END')

BEGIN
END

# basic checks on team and player name dictionaries, currently:

# checks for duplicate entries.

In [7]:
print('BEGIN')

if(number_of_games_per_match != 3 and number_of_games_per_match != 7):
    raise SystemExit('number_of_games_per_match != 3 and number_of_games_per_match != 7:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
if(number_of_matches_per_match != 5):
    raise SystemExit('number_of_matches_per_match != 5:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
if( len(Unique_Team_Names) != len(set(Unique_Team_Names)) ):
    raise SystemExit('Team name dictionary, Unique_Team_Names, might have a duplicate entry:'+__file__+' line number: '+str(inspect.stack()[0][2]))

if( len(Unique_Player_Ranking) != len(set(Unique_Player_Ranking)) ):
    raise SystemExit('Player name dictionary, player_ranking, might have a duplicate entry:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
if( len(Unique_Team_Names) < number_teams ):
    raise SystemExit('len(Unique_Team_Names) < number_teams:'+__file__+' line number: '+str(inspect.stack()[0][2]))

print('END')

BEGIN
END

# Scan for optimal number of sections and teams/players per section.

In [7]:
print('BEGIN')

if(diag): print('Unique_Player_Ranking=',Unique_Player_Ranking)
if(diag): print('number of players=',number_of_players)

#try_6_sections

if(diag): print('number_teams=',number_teams)

if(True): print('Want as many 6 player teams as possible...')

if(True): print('average number of players for 6 section team=', \
      number_of_players / (6 * number_players_per_team))

if(True): print('average number of players for 4 section team=', \
      number_of_players / (4 * number_players_per_team))

#try combination of 4 and 6 teams.

for number_four_team_sections in range(number_sections+1):
    if(True): print('number_four_team_sections=',number_four_team_sections)

    total_teams = number_four_team_sections*4 + (number_sections-number_four_team_sections)*6
    
    ratio = total_teams / number_teams
    
    if(diag): print('ratio=',ratio)
    
    if( total_teams % number_teams == 0): \
        print(CRED+'For '+str(number_teams)+' teams with '+str(number_sections)+' sections, optimum is '+ \
              str(number_four_team_sections)+' four player teams and '+ \
              str(number_sections-number_four_team_sections)+' six player teams.'+CEND )
    
    if(diag): print('total_teams=',total_teams)
        
print('END')

BEGIN
Want as many 6 player teams as possible...
average number of players for 6 section team= 5.333333333333333
average number of players for 4 section team= 8.0

NameError: name 'number_sections' is not defined

# Generate section_team_df dataframe

In [8]:
print('BEGIN')

#from this can specify:

if(Pennant=="Wednesday Night"):
    number_teams_per_section = [6, 8, 6, 6, 6, 6, 4, 4]
elif(Pennant=="Thursday Night"):
    number_teams_per_section = [4, 6, 6, 6, 6, 4]
elif(Pennant=="Monday Morning"):
    number_teams_per_section = [6, 6, 6, 4]
elif(Pennant=="Thursday Morning"):
    number_teams_per_section = [6, 6, 6, 6]
else:
    raise SystemExit('Pennant, '+Pennant+'Does not exist:'+__file__+' line number: '+str(inspect.stack()[0][2]))

number_sections = len(number_teams_per_section)

# tables_per_section = []
# for teams in number_teams_per_section:
#     tables_per_section.append(int(teams/2))

# tables_per_section = generate_tables_per_section(diag, number_teams_per_section)

section_players_raw = []
player_index_beg = 0
for cnt,section0 in enumerate(range(number_sections)):
    if(diag): print(cnt,section0)
    player_index_end = player_index_beg + number_teams_per_section[cnt]*2 -1

    if(diag): print(player_index_beg, player_index_end)
    
    if(diag): print('Section ',section0+1,'.:')
    if(diag): print(Unique_Player_Ranking[player_index_beg:player_index_end+1])
    
    section_players_raw.append(Unique_Player_Ranking[player_index_beg:player_index_end+1])
    
    player_index_beg = player_index_end + 1

for cnt,section0 in enumerate(range(number_sections)):
    #print(section_players_raw[cnt])
    players_1 = section_players_raw[cnt][0:number_teams_per_section[cnt]]
    players_2_tmp = section_players_raw[cnt][number_teams_per_section[cnt]::]
    players_2 = players_2_tmp[::-1]
    if(diag): print(section0+1,players_1,players_2)

section_list,team_list,team_name_list,player1_list,player2_list = [],[],[],[],[]
total_team_count = 0
for cnt,section0 in enumerate(range(number_sections)):
    for team0 in range(number_teams_per_section[cnt]):
        total_team_count += 1
        
        players_1 = section_players_raw[cnt][0:number_teams_per_section[cnt]]
        players_2_tmp = section_players_raw[cnt][number_teams_per_section[cnt]::][::-1]
        if(diag): print('section=',section0+1,' team=',team0+1,' team name=','Animal '+str(total_team_count)+ \
        ' player1='+players_1[team0]+' player2='+players_2_tmp[team0])
        section_list.append(section0+1)
        team_list.append(team0+1)
#         team_name_list.append('Animal '+str(total_team_count))
        team_name_list.append(Unique_Team_Names[total_team_count-1])
        player1_list.append(players_1[team0])
        player2_list.append(players_2_tmp[team0])
        
section_team_composition_df = pd.DataFrame({'Section': section_list, \
                   'Team' : team_list, \
                   'Team Name': team_name_list, \
                   'Player 1': player1_list, \
                   'Player 2': player2_list \
                  })

display(section_team_composition_df)

print('END')

BEGIN

    Section  Team        Team Name            Player 1              Player 2
0         1     1        Bandicoot  Bhiwarkar, Mangesh        Gubicak, Peter
1         1     2            Bilby       Keating, John         Collier, Mark
2         1     3           Brolga        Pilz, Lothar       Harrison, Leigh
3         1     4        Cassowary     Harris, Lachlan     Weighell, Michael
4         2     1         Cockatoo     Signor, Dominic             Jung, Tad
5         2     2        Crocodile   Goodridge, Robert   Probyn-Smith, Garth
6         2     3            Dingo       Kung, Bernard       Oldham, Cameron
7         2     4          Dolphin      Signor, Sergio         Talolin, Nick
8         2     5           Dugong         Dyer, Terry    Straughair, Thomas
9         2     6          Echidna      Goepfert, Paul             Holt, Ben
10        3     1              Emu          Ryan, Paul      O'Regan, Brendan
11        3     2    Fairy Penguin         Zeng, Jimmy   Salgueiro, Fernando
12        3     3       Flying Fox     Jefimenko, Paul   Mazzaferri, Michael
13        3     4         Fur Seal       Morgan, Shane         Mendes, Champ
14        3     5            Galah        Lee, Johnson          Howse, Kalan
15        3     6           Goanna     Mcerlain, Peter          Powell, John
16        4     1             Ibis  Zdimirovic, Zoltan       Harrison, Schae
17        4     2         Kangaroo        Goodwin, Jim           Hyde, David
18        4     3            Koala       Smythe, David        Thomson, Jamie
19        4     4       Kookaburra       Blattman, Ben        Ponsonby, Mark
20        4     5           Lizard        Byrne, Jason           Ryan, Chris
21        4     6         Lyrebird     Thompson, David     Shamakhy, Alireza
22        5     1           Magpie         Emam, Arash  Salgueiro, Christian
23        5     2           Numbat   Mazzaferri, Henry         Ballment, Meg
24        5     3         Platypus     Darlow, Anthony          Short, Craig
25        5     4           Possum     Harrison, Peter          Mujica, Jose
26        5     5           Quokka    Timmermans,David        Symes, Brendon
27        5     6            Quoll     Van Veen, Peter          Rewell, Luke
28        6     1             Seal     Wakefield, Paul         Nguyen, Khanh
29        6     2     Sugar Glider     Falconer, Colin      Winsemius, Karen
30        6     3  Tasmanian Devil       Powell, Robyn         Jordan, Julia
31        6     4           Turtle       Florey, Linda      Dodson, Michelle

END

# Generate round/date info. for whole season.

In [9]:
print('BEGIN')

YYYYMMDD = []

#number_teams_per_section = [4, 6, 6, 6, 6, 4] #5 an option with 2 rounds of finals.

#number_sections = len(number_teams_per_section)

number_players_per_section = []
for cnt,section0 in enumerate(range(number_sections)):
    number_players_per_section.append(number_teams_per_section[cnt]*number_players_per_team)

one_week = timedelta(days=7)

for holiday_match in holiday_nomatches:
   if(holiday_match == first_round): \
        raise SystemExit('Set first round not to be a holiday round:'+__file__+' line number: '+str(inspect.stack()[0][2]))

found_rounds0 = 0

for round0 in range(99):
    
    current_round = first_round+one_week*round0
    
    holiday_clash=False
    for holiday_match in holiday_nomatches:
        if(holiday_match == current_round):
            if(diag): print('same')
            holiday_clash=True
        else:
            if(diag): print('not same')

    if(holiday_clash): print(CRED+'holiday_clash='+str(current_round)+CEND)
                
    if(not holiday_clash):
        found_rounds0 += 1
        YYYYMMDD.append(str(current_round))
        print(CGREEN+'round [1]='+str(found_rounds0)+' date='+str(current_round)+CEND)

        for section0 in range(number_sections):
            if(number_teams_per_section[section0]==4):
                if(found_rounds0==number_rounds):
                    finals=True
                else:
                    finals=False
            elif(number_teams_per_section[section0]==6):
                finals=False
            else:
                raise SystemExit('number of teams per section can only be 4 or 6:'+__file__+' line number: '+str(inspect.stack()[0][2]))
            print('section=',section0+1,' finals=',finals)
    
    if(found_rounds0 == number_rounds):
        #print('Finished')
        raise SystemExit('Finished.')

print('END')

BEGIN
round [1]=1 date=2019-07-18
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=2 date=2019-07-25
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=3 date=2019-08-01
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=4 date=2019-08-08
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=5 date=2019-08-15
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=6 date=2019-08-22
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=7 date=2019-08-29
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=8 date=2019-09-05
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=9 date=2019-09-12
section= 1  finals= False
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= False
round [1]=10 date=2019-09-19
section= 1  finals= True
section= 2  finals= False
section= 3  finals= False
section= 4  finals= False
section= 5  finals= False
section= 6  finals= True

SystemExit: Finished.

/anaconda3/envs/qbo_new/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

# Generate matches for all sections for whole season.

# This based on 2 person team. Would take further work to generalise
# e.g. 3 person team.

In [15]:
print('BEGIN')

#number_sets : the number of times the current group of matches needs to be used. If we have 4 team sections
#then there are 3, so some teams will play 2 home matches and others 1. If we have 6 team sections then all
#teams will play 1 home and 1 away match.
    
#overall_order_of_play_by_section = []
all_sections_all_rounds = ()
for cnt,current_number_teams_per_section in enumerate(number_teams_per_section):
    if(diag): print('cnt=',cnt)

    this_section_all_rounds = []
    if(current_number_teams_per_section==4):
        number_sets = 3
        matches_per_round = 2
    elif(current_number_teams_per_section==6):
        number_sets = 2
        matches_per_round = 3
    else:
        raise SystemExit('Only 4/6 valid:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    for number_set in range(number_sets):
        #print('number_set,number_set%number_sets=',number_set,number_set%number_sets)
        
        #alternatively switch:
        if(number_set%2==0):
            #print('normal')
            j = order_of_play_one_iteration(False, current_number_teams_per_section)
            #print('j=',j)
            
            this_section_all_rounds += chunk_them(diag, j, matches_per_round)
            
            #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
        else:
            #print('reverse')
            j = order_of_play_one_iteration(False, current_number_teams_per_section)
            #print('j=',j)
            k = reverse_home_team(diag, j )
            #print('k=',k)
            this_section_all_rounds += chunk_them(diag, k, matches_per_round)
            
    if(current_number_teams_per_section==4): #this is for finals.
        this_section_all_rounds += [[[None, None], [None, None]]]
 
    if(diag): print('cnt,this_section_all_rounds=',cnt,this_section_all_rounds)
    
    all_sections_all_rounds += (this_section_all_rounds,)
    
all_sections_all_rounds = list(all_sections_all_rounds) #convert back to a list.

if(True): print('all_sections_all_rounds=',all_sections_all_rounds)

if(True): print('len(all_sections_all_rounds)=',len(all_sections_all_rounds))

#can pull out any section/round/match, currently will bomb if item doesn't exist.
SECTION0 = 5
ROUND0 = -2
MATCH0 = 0

if(diag): print(all_sections_all_rounds[SECTION0][ROUND0][MATCH0])

print('END')

BEGIN
all_sections_all_rounds= [[[[1, 2], [3, 4]], [[1, 3], [2, 4]], [[1, 4], [2, 3]], [[2, 1], [4, 3]], [[3, 1], [4, 2]], [[4, 1], [3, 2]], [[1, 2], [3, 4]], [[1, 3], [2, 4]], [[1, 4], [2, 3]], [[None, None], [None, None]]], [[[1, 2], [4, 6], [3, 5]], [[1, 3], [2, 6], [4, 5]], [[5, 6], [1, 4], [2, 3]], [[1, 5], [3, 6], [2, 4]], [[1, 6], [2, 5], [3, 4]], [[2, 1], [6, 4], [5, 3]], [[3, 1], [6, 2], [5, 4]], [[6, 5], [4, 1], [3, 2]], [[5, 1], [6, 3], [4, 2]], [[6, 1], [5, 2], [4, 3]]], [[[1, 2], [4, 6], [3, 5]], [[1, 3], [2, 6], [4, 5]], [[5, 6], [1, 4], [2, 3]], [[1, 5], [3, 6], [2, 4]], [[1, 6], [2, 5], [3, 4]], [[2, 1], [6, 4], [5, 3]], [[3, 1], [6, 2], [5, 4]], [[6, 5], [4, 1], [3, 2]], [[5, 1], [6, 3], [4, 2]], [[6, 1], [5, 2], [4, 3]]], [[[1, 2], [4, 6], [3, 5]], [[1, 3], [2, 6], [4, 5]], [[5, 6], [1, 4], [2, 3]], [[1, 5], [3, 6], [2, 4]], [[1, 6], [2, 5], [3, 4]], [[2, 1], [6, 4], [5, 3]], [[3, 1], [6, 2], [5, 4]], [[6, 5], [4, 1], [3, 2]], [[5, 1], [6, 3], [4, 2]], [[6, 1], [5, 2], [4, 3]]], [[[1, 2], [4, 6], [3, 5]], [[1, 3], [2, 6], [4, 5]], [[5, 6], [1, 4], [2, 3]], [[1, 5], [3, 6], [2, 4]], [[1, 6], [2, 5], [3, 4]], [[2, 1], [6, 4], [5, 3]], [[3, 1], [6, 2], [5, 4]], [[6, 5], [4, 1], [3, 2]], [[5, 1], [6, 3], [4, 2]], [[6, 1], [5, 2], [4, 3]]], [[[1, 2], [3, 4]], [[1, 3], [2, 4]], [[1, 4], [2, 3]], [[2, 1], [4, 3]], [[3, 1], [4, 2]], [[4, 1], [3, 2]], [[1, 2], [3, 4]], [[1, 3], [2, 4]], [[1, 4], [2, 3]], [[None, None], [None, None]]]]
len(all_sections_all_rounds)= 6
END

# Automatically allocate tables per round, section and match

In [16]:
print('BEGIN')

#tables_per_section = generate_tables_per_section(diag, number_teams_per_section)

#test data:
#ok
number_teams_per_section = [4, 6, 6, 6, 6, 4]
number_sections = len(number_teams_per_section)
groups_of_n = 3

#ok
# number_teams_per_section = [6, 6, 6, 6, 6, 6]
# number_sections = len(number_teams_per_section)
# groups_of_n = 3

#ok
# number_teams_per_section = [4, 4, 4, 4, 4, 4]
# number_sections = len(number_teams_per_section)
# groups_of_n = 2

#ok
# number_teams_per_section = [6, 4, 6, 4, 6, 4]
# number_sections = len(number_teams_per_section)
# groups_of_n = 3

#ok
# number_teams_per_section = [8, 6, 6, 6, 8]
# number_sections = len(number_teams_per_section)
# groups_of_n = 4

################################################################################

#comment out if testing above:
groups_of_n = 3 #this number is to be the size of the largest table requirement of a section.

table_max = 22 #do not allocate beyond 22. Table 23 is reserve for training, so good to keep one space at least.

table_init = 11 #start from this table, which is the first table in the new room.

all_sections_all_rounds_tables = automatic_table_allocation(diag, number_teams_per_section, number_rounds, groups_of_n, table_max, table_init)

#print('all_sections_all_rounds_tables=', all_sections_all_rounds_tables)

table_allocation_dict = {}
table_allocation_dict['Round'] = range(1,number_rounds+1)
for section0 in range(len(number_teams_per_section)):
    table_allocation_dict['Section '+str(section0+1)] = all_sections_all_rounds_tables[section0]

table_allocation_df = pd.DataFrame(table_allocation_dict)

display(table_allocation_df)

print('END')

BEGIN

,Round,Section 1,Section 2,Section 3,Section 4,Section 5,Section 6
0,1,"[11, 12]","[14, 15, 16]","[17, 18, 19]","[20, 21, 22]","[1, 2, 3]","[4, 5]"
1,2,"[4, 5]","[11, 12, 13]","[14, 15, 16]","[17, 18, 19]","[20, 21, 22]","[1, 2]"
2,3,"[1, 2]","[4, 5, 6]","[11, 12, 13]","[14, 15, 16]","[17, 18, 19]","[20, 21]"
3,4,"[20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15, 16]","[17, 18]"
4,5,"[17, 18]","[20, 21, 22]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15]"
5,6,"[14, 15]","[17, 18, 19]","[20, 21, 22]","[1, 2, 3]","[4, 5, 6]","[11, 12]"
6,7,"[11, 12]","[14, 15, 16]","[17, 18, 19]","[20, 21, 22]","[1, 2, 3]","[4, 5]"
7,8,"[4, 5]","[11, 12, 13]","[14, 15, 16]","[17, 18, 19]","[20, 21, 22]","[1, 2]"
8,9,"[1, 2]","[4, 5, 6]","[11, 12, 13]","[14, 15, 16]","[17, 18, 19]","[20, 21]"
9,10,"[20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15, 16]","[17, 18]"

END

In [17]:
print('BEGIN')

all_sections_all_rounds_tables_override = [ \
[ [11,12],    [14,15],    [17,18],    [20,21],    [1, 2],     [4,5],      [11,12],    [14,15],    [17,18],    [20,21] ], \
[ [13,14,15], [16,17,18], [19,20,21], [1,2,3],    [3,4,5],    [11,12,13], [13,14,15], [16,17,18], [19,20,21], [1,2,3] ], \
[ [16,17,18], [19,20,21], [1,2,3],    [4,5,6],    [11,12,13], [14,15,16], [16,17,18], [19,20,21], [1,2,3],    [4,5,6] ], \
[ [19,20,21], [1,2,3],    [4,5,6],    [11,12,13], [14,15,16], [17,18,19], [19,20,21], [1,2,3],    [4,5,6],    [11,12,13] ], \
[ [1,2,3],    [4,5,6],    [11,12,13], [14,15,16], [17,18,19], [20,21,1],  [1,2,3],    [4,5,6],    [11,12,13], [14,15,16] ], \
[ [4,5],      [11,12],    [14,15],    [17,18],    [20,21],    [2,3],      [4,5],      [11,12],    [14,15],    [17,18] ], \
]

table_allocation_dict = {}
table_allocation_dict['Round'] = range(1,number_rounds+1)
for section0 in range(len(number_teams_per_section)):
    table_allocation_dict['Section '+str(section0+1)] = all_sections_all_rounds_tables_override[section0]

table_allocation_override_df = pd.DataFrame(table_allocation_dict)

display(table_allocation_override_df)

if(override_table):
    print(CRED+'Override tables to comform to printed/online version...'+CEND)
    all_sections_all_rounds_tables = list(all_sections_all_rounds_tables_override)
    
#section,ROUND,match = 1,1,1

#print(all_sections_all_rounds_tables[section-1][ROUND-1][match-1]) #.split(',')[0])

print('END')

BEGIN

,Round,Section 1,Section 2,Section 3,Section 4,Section 5,Section 6
0,1,"[11, 12]","[13, 14, 15]","[16, 17, 18]","[19, 20, 21]","[1, 2, 3]","[4, 5]"
1,2,"[14, 15]","[16, 17, 18]","[19, 20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12]"
2,3,"[17, 18]","[19, 20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15]"
3,4,"[20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15, 16]","[17, 18]"
4,5,"[1, 2]","[3, 4, 5]","[11, 12, 13]","[14, 15, 16]","[17, 18, 19]","[20, 21]"
5,6,"[4, 5]","[11, 12, 13]","[14, 15, 16]","[17, 18, 19]","[20, 21, 1]","[2, 3]"
6,7,"[11, 12]","[13, 14, 15]","[16, 17, 18]","[19, 20, 21]","[1, 2, 3]","[4, 5]"
7,8,"[14, 15]","[16, 17, 18]","[19, 20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12]"
8,9,"[17, 18]","[19, 20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15]"
9,10,"[20, 21]","[1, 2, 3]","[4, 5, 6]","[11, 12, 13]","[14, 15, 16]","[17, 18]"

Override tables to comform to printed/online version...
END

In [18]:
print('BEGIN')

sections_1and6 = [ \
                  [[1, 3], [2, 4]], \
                  [[4, 1], [3, 2]], \
                  [[1, 2], [4, 3]], \
                  [[3, 1], [2, 4]], \
                  [[1, 4], [2, 3]], \
                  [[2, 1], [3, 4]], \
                  [[1, 3], [2, 4]], \
                  [[4, 1], [3, 2]], \
                  [[3, 4], [2, 1]], \
                  [[None, None], [None, None]] \
                 ]

sections_2to5 = [ \
                 [[1, 6], [2, 5], [3, 4]], \
                 [[5, 1], [4, 2], [6, 3]], \
                 [[1, 4], [3, 2], [5, 6]], \
                 [[3, 1], [2, 6], [4, 5]], \
                 [[1, 2], [5, 3], [6, 4]], \
                 [[6, 1], [5, 2], [4, 3]], \
                 [[1, 5], [2, 4], [3, 6]], \
                 [[4, 1], [2, 3], [6, 5]], \
                 [[1, 3], [6, 2], [5, 4]], \
                 [[2, 1], [3, 5], [4, 6]] \
                ]

all_sections_all_rounds_override = ( sections_1and6,)
all_sections_all_rounds_override += ( sections_2to5,)
all_sections_all_rounds_override += ( sections_2to5,)
all_sections_all_rounds_override += ( sections_2to5,)
all_sections_all_rounds_override += ( sections_2to5,)
all_sections_all_rounds_override += ( sections_1and6,)

print('all_sections_all_rounds_override=',all_sections_all_rounds_override)
print('len(all_sections_all_rounds_override)=',len(all_sections_all_rounds_override))

if(override_draw):
    print(CRED+'Override section/match orders to comform to printed/online version...'+CEND)
    all_sections_all_rounds = list(all_sections_all_rounds_override)

print('END')

BEGIN
all_sections_all_rounds_override= ([[[1, 3], [2, 4]], [[4, 1], [3, 2]], [[1, 2], [4, 3]], [[3, 1], [2, 4]], [[1, 4], [2, 3]], [[2, 1], [3, 4]], [[1, 3], [2, 4]], [[4, 1], [3, 2]], [[3, 4], [2, 1]], [[None, None], [None, None]]], [[[1, 6], [2, 5], [3, 4]], [[5, 1], [4, 2], [6, 3]], [[1, 4], [3, 2], [5, 6]], [[3, 1], [2, 6], [4, 5]], [[1, 2], [5, 3], [6, 4]], [[6, 1], [5, 2], [4, 3]], [[1, 5], [2, 4], [3, 6]], [[4, 1], [2, 3], [6, 5]], [[1, 3], [6, 2], [5, 4]], [[2, 1], [3, 5], [4, 6]]], [[[1, 6], [2, 5], [3, 4]], [[5, 1], [4, 2], [6, 3]], [[1, 4], [3, 2], [5, 6]], [[3, 1], [2, 6], [4, 5]], [[1, 2], [5, 3], [6, 4]], [[6, 1], [5, 2], [4, 3]], [[1, 5], [2, 4], [3, 6]], [[4, 1], [2, 3], [6, 5]], [[1, 3], [6, 2], [5, 4]], [[2, 1], [3, 5], [4, 6]]], [[[1, 6], [2, 5], [3, 4]], [[5, 1], [4, 2], [6, 3]], [[1, 4], [3, 2], [5, 6]], [[3, 1], [2, 6], [4, 5]], [[1, 2], [5, 3], [6, 4]], [[6, 1], [5, 2], [4, 3]], [[1, 5], [2, 4], [3, 6]], [[4, 1], [2, 3], [6, 5]], [[1, 3], [6, 2], [5, 4]], [[2, 1], [3, 5], [4, 6]]], [[[1, 6], [2, 5], [3, 4]], [[5, 1], [4, 2], [6, 3]], [[1, 4], [3, 2], [5, 6]], [[3, 1], [2, 6], [4, 5]], [[1, 2], [5, 3], [6, 4]], [[6, 1], [5, 2], [4, 3]], [[1, 5], [2, 4], [3, 6]], [[4, 1], [2, 3], [6, 5]], [[1, 3], [6, 2], [5, 4]], [[2, 1], [3, 5], [4, 6]]], [[[1, 3], [2, 4]], [[4, 1], [3, 2]], [[1, 2], [4, 3]], [[3, 1], [2, 4]], [[1, 4], [2, 3]], [[2, 1], [3, 4]], [[1, 3], [2, 4]], [[4, 1], [3, 2]], [[3, 4], [2, 1]], [[None, None], [None, None]]])
len(all_sections_all_rounds_override)= 6
Override section/match orders to comform to printed/online version...
END

# Display draw (date & team combinations)

In [19]:
print('BEGIN')

draw_all_df = make_draw(diag, all_sections_all_rounds, YYYYMMDD)

#print(len(draw_all_df))

for draw_one in draw_all_df:
    display(draw_one)
        
print('END')

BEGIN

   Round        Date                       Matches
0      1  2019-07-18              [[1, 3], [2, 4]]
1      2  2019-07-25              [[4, 1], [3, 2]]
2      3  2019-08-01              [[1, 2], [4, 3]]
3      4  2019-08-08              [[3, 1], [2, 4]]
4      5  2019-08-15              [[1, 4], [2, 3]]
5      6  2019-08-22              [[2, 1], [3, 4]]
6      7  2019-08-29              [[1, 3], [2, 4]]
7      8  2019-09-05              [[4, 1], [3, 2]]
8      9  2019-09-12              [[3, 4], [2, 1]]
9     10  2019-09-19  [[None, None], [None, None]]

   Round        Date                   Matches
0      1  2019-07-18  [[1, 6], [2, 5], [3, 4]]
1      2  2019-07-25  [[5, 1], [4, 2], [6, 3]]
2      3  2019-08-01  [[1, 4], [3, 2], [5, 6]]
3      4  2019-08-08  [[3, 1], [2, 6], [4, 5]]
4      5  2019-08-15  [[1, 2], [5, 3], [6, 4]]
5      6  2019-08-22  [[6, 1], [5, 2], [4, 3]]
6      7  2019-08-29  [[1, 5], [2, 4], [3, 6]]
7      8  2019-09-05  [[4, 1], [2, 3], [6, 5]]
8      9  2019-09-12  [[1, 3], [6, 2], [5, 4]]
9     10  2019-09-19  [[2, 1], [3, 5], [4, 6]]

END

# generate DataFrame with all information for whole season.

In [20]:
print('BEGIN')

#json_status = 0 #ignore files in main_draw_df creation.
#json_status = 1 #read only validated files
#json_status = 2 #read only raw files
#json_status = 3 #read both validated and raw files

if(json_status == 0):
    print('Ignoring all json files.')
elif(json_status == 1):
    print('Reading only validated json files.')
elif(json_status == 2):
    print('Reading only raw json files.')
elif(json_status == 3):
    print('Reading both validated and raw json files.')
else:
    raise SystemExit('function: invalid json_status value.'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
unique_match0 = -1
unique_matchs0 = []
rounds0 = []
sections0 = []
matchs0 = []
results0 = []
dates0 = []
tables0 = []

team1_player1s0 = []
team1_player2s0 = []

team2_player1s0 = []
team2_player2s0 = []

team1s0 = []
team2s0 = []

empty_5xN = [         [[], []],  \
                      [[], []], \
                      [[], []], \
                      [[], []], \
                      [[], []], ]

current_entries = 0

simple_table = True #create simple table allocation, will not be functinal though.
simple_table = False

for round0 in range(number_rounds):
    table_this_round0 = -1
    for section0 in range(len(number_teams_per_section)):
        for match0 in range(int(number_teams_per_section[section0]/number_players_per_team)):
            table_this_round0 +=1
            
            unique_match0 += 1

            #print('unique_match0,round0,section0,match0=',unique_match0,round0,section0,match0)
            unique_matchs0.append(unique_match0+1)
            rounds0.append(round0+1)
            dates0.append(YYYYMMDD[round0])
            sections0.append(section0+1)
            matchs0.append(match0+1)
            
#             section,ROUND,match = 1,1,1

#             print(all_sections_all_rounds_tables[section-1][ROUND-1][match-1]) #.split(',')[0])

                #heiden

            if(simple_table):
                tables0.append(table_this_round0+1)
            else:
                tables0.append(all_sections_all_rounds_tables[section0][round0][match0])
            #results0.append(empty_5xN)
            
            input_json_file = 'section_'+'{0:02d}'.format(section0+1)+'_round_'+'{0:02d}'.format(round0+1)+'_match_'+'{0:02d}'.format(match0+1)+'_data.json'
            #test json files and load data if required:
            file1 = json_directory+'/'+input_json_file
            file2 = validated_json_directory+'/'+input_json_file
            if(os.path.exists(file1) and os.path.exists(file2)):
                raise SystemExit('os.path.exists(file1) and os.path.exists(file2), sort this out before we can continue.'+__file__+' line number: '+str(inspect.stack()[0][2]))

#json_status = 0 #ignore files in main_draw_df creation.
#json_status = 1 #read only validated files
#json_status = 2 #read only raw files
#json_status = 3 #read both validated and raw files

            iswitch = 0
            if(json_status > 0):
                if(os.path.exists(json_directory+'/'+input_json_file) and (json_status == 2 or json_status == 3)):
                    iswitch += 1
                    print(CRED+json_directory+'/'+input_json_file+' exists...loading'+CEND)
                    json_match_df = pd.read_json(r''+json_directory+'/'+input_json_file, orient=json_orient)
                    results0.append(match_5xN(diag, json_match_df, number_of_games_per_match))

                if(os.path.exists(validated_json_directory+'/'+input_json_file) and (json_status == 1 or json_status == 3)):
                    iswitch += 1
                    print(CRED+validated_json_directory+'/'+input_json_file+' exists...loading'+CEND)
                    json_match_df = pd.read_json(r''+validated_json_directory+'/'+input_json_file, orient=json_orient)
                    results0.append(match_5xN(diag, json_match_df, number_of_games_per_match))

            if(iswitch == 0):
                results0.append(empty_5xN)
      
                #print(match_5xN(False, j_df, number_of_games_per_match))
            
            extract_one = all_sections_all_rounds[section0][round0][match0]
    
            #print('extract_one=',extract_one)
            #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
            
            if(extract_one[0]==None):
                team1s0.append('Team A Dummy')
                team1_player1s0.append('Player1 Dummy')
                team1_player2s0.append('Player2 Dummy')
            
            else:
                section_teamA = section_team_composition_df.query('Section == '+str(section0+1)).query('Team == '+str(extract_one[0])).values
                team1_player1s0.append(section_teamA[0][3])
                team1_player2s0.append(section_teamA[0][4])
                team1s0.append('Team ' + str(extract_one[0])+': '+section_teamA[0][2])
                
                #print('xxx=',section_teamA[0][2])
                #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

            if(extract_one[1]==None):
                team2s0.append('Team B Dummy')
                team2_player1s0.append('Player1 Dummy')
                team2_player2s0.append('Player2 Dummy')
            
            else:
                section_teamB = section_team_composition_df.query('Section == '+str(section0+1)).query('Team == '+str(extract_one[1])).values
                team2_player1s0.append(section_teamB[0][3])
                team2_player2s0.append(section_teamB[0][4])
                team2s0.append('Team ' + str(extract_one[1])+': '+section_teamB[0][2])
        
#             print('section_teamA=',section_teamA)
#             print('section_teamB=',section_teamB)
            
            #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

print('unique_match0=',unique_match0)

#section_team_composition_df.loc[ (section_team_composition_df['Section'] == 1) & (section_team_composition_df['Team Name'] == 'Bandicoot') ]

full_table_df = pd.DataFrame({ \
                        'Unique match': unique_matchs0, \
                        'Round': rounds0, \
                        'Match Date' : dates0, \
                        'Section' : sections0, \
                        'Match' : matchs0, \
                        'Table' : tables0, \
                        'Team1' : team1s0, \
                        'Team1 Player1': team1_player1s0, \
                        'Team1 Player2': team1_player2s0, \
                        'Team2': team2s0, \
                        'Team2 Player1': team2_player1s0, \
                        'Team2 Player2': team2_player2s0, \

                        'Result': results0, \
                  })

pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 400)
pd.set_option('display.max_colwidth', -1)

display(full_table_df)

full_table_df.to_json(r'full_table.json')

print('END')

BEGIN
Reading both validated and raw json files.
cdtta_thursday_night_json/validated/section_01_round_01_match_01_data.json exists...loading
cdtta_thursday_night_json/validated/section_01_round_01_match_02_data.json exists...loading
unique_match0= 159

,Unique match,Round,Match Date,Section,Match,Table,Team1,Team1 Player1,Team1 Player2,Team2,Team2 Player1,Team2 Player2,Result
0,1,1,2019-07-18,1,1,11,Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter",Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh","[[[11, 3, 11, 13, 11, 0, 0], [8, 11, 9, 11, 9, 0, 0]], [[11, 3, 11, 13, 11, 0, 0], [9, 11, 9, 11, 9, 0, 0]], [[11, 3, 11, 13, 11, 0, 0], [9, 11, 9, 11, 9, 0, 0]], [[11, 3, 11, 13, 11, 0, 0], [9, 11, 9, 11, 9, 0, 0]], [[11, 4, 11, 13, 11, 0, 0], [9, 11, 9, 11, 9, 0, 0]]]"
1,2,1,2019-07-18,1,2,12,Team 2: Bilby,"Keating, John","Collier, Mark",Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael","[[[0, 0, 0, 0, 0, 0, 0], [11, 11, 11, 11, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0], [11, 11, 11, 11, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0], [11, 11, 11, 11, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0], [11, 11, 11, 11, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0], [11, 11, 11, 11, 0, 0, 0]]]"
2,3,1,2019-07-18,2,1,13,Team 1: Cockatoo,"Signor, Dominic","Jung, Tad",Team 6: Echidna,"Goepfert, Paul","Holt, Ben","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
3,4,1,2019-07-18,2,2,14,Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth",Team 5: Dugong,"Dyer, Terry","Straughair, Thomas","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
4,5,1,2019-07-18,2,3,15,Team 3: Dingo,"Kung, Bernard","Oldham, Cameron",Team 4: Dolphin,"Signor, Sergio","Talolin, Nick","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
5,6,1,2019-07-18,3,1,16,Team 1: Emu,"Ryan, Paul","O'Regan, Brendan",Team 6: Goanna,"Mcerlain, Peter","Powell, John","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
6,7,1,2019-07-18,3,2,17,Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando",Team 5: Galah,"Lee, Johnson","Howse, Kalan","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
7,8,1,2019-07-18,3,3,18,Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael",Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
8,9,1,2019-07-18,4,1,19,Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae",Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
9,10,1,2019-07-18,4,2,20,Team 2: Kangaroo,"Goodwin, Jim","Hyde, David",Team 5: Lizard,"Byrne, Jason","Ryan, Chris","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
10,11,1,2019-07-18,4,3,21,Team 3: Koala,"Smythe, David","Thomson, Jamie",Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
11,12,1,2019-07-18,5,1,1,Team 1: Magpie,"Emam, Arash","Salgueiro, Christian",Team 6: Quoll,"Van Veen, Peter","Rewell, Luke","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
12,13,1,2019-07-18,5,2,2,Team 2: Numbat,"Mazzaferri, Henry","Ballment, Meg",Team 5: Quokka,"Timmermans,David","Symes, Brendon","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
13,14,1,2019-07-18,5,3,3,Team 3: Platypus,"Darlow, Anthony","Short, Craig",Team 4: Possum,"Harrison, Peter","Mujica, Jose","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
14,15,1,2019-07-18,6,1,4,Team 1: Seal,"Wakefield, Paul","Nguyen, Khanh",Team 3: Tasmanian Devil,"Powell, Robyn","Jordan, Julia","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
15,16,1,2019-07-18,6,2,5,Team 2: Sugar Glider,"Falconer, Colin","Winsemius, Karen",Team 4: Turtle,"Florey, Linda","Dodson, Michelle","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
16,17,2,2019-07-25,1,1,14,Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael",Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
17,18,2,2019-07-25,1,2,15,Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh",Team 2: Bilby,"Keating, John","Collier, Mark","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
18,19,2,2019-07-25,2,1,16,Team 5: Dugong,"Dyer, Terry","Straughair, Thomas",Team 1: Cockatoo,"Signor, Dominic","Jung, Tad","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
19,20,2,2019-07-25,2,2,17,Team 4: Dolphin,"Signor, Sergio","Talolin, Nick",Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
20,21,2,2019-07-25,2,3,18,Team 6: Echidna,"Goepfert, Paul","Holt, Ben",Team 3: Dingo,"Kung, Bernard","Oldham, Cameron","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
21,22,2,2019-07-25,3,1,19,Team 5: Galah,"Lee, Johnson","Howse, Kalan",Team 1: Emu,"Ryan, Paul","O'Regan, Brendan","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
22,23,2,2019-07-25,3,2,20,Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ",Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
23,24,2,2019-07-25,3,3,21,Team 6: Goanna,"Mcerlain, Peter","Powell, John",Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
24,25,2,2019-07-25,4,1,1,Team 5: Lizard,"Byrne, Jason","Ryan, Chris",Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
25,26,2,2019-07-25,4,2,2,Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark",Team 2: Kangaroo,"Goodwin, Jim","Hyde, David","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
26,27,2,2019-07-25,4,3,3,Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza",Team 3: Koala,"Smythe, David","Thomson, Jamie","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
27,28,2,2019-07-25,5,1,4,Team 5: Quokka,"Timmermans,David","Symes, Brendon",Team 1: Magpie,"Emam, Arash","Salgueiro, Christian","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
28,29,2,2019-07-25,5,2,5,Team 4: Possum,"Harrison, Peter","Mujica, Jose",Team 2: Numbat,"Mazzaferri, Henry","Ballment, Meg","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
29,30,2,2019-07-25,5,3,6,Team 6: Quoll,"Van Veen, Peter","Rewell, Luke",Team 3: Platypus,"Darlow, Anthony","Short, Craig","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
30,31,2,2019-07-25,6,1,11,Team 4: Turtle,"Florey, Linda","Dodson, Michelle",Team 1: Seal,"Wakefield, Paul","Nguyen, Khanh","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
31,32,2,2019-07-25,6,2,12,Team 3: Tasmanian Devil,"Powell, Robyn","Jordan, Julia",Team 2: Sugar Glider,"Falconer, Colin","Winsemius, Karen","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
32,33,3,2019-08-01,1,1,17,Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter",Team 2: Bilby,"Keating, John","Collier, Mark","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
33,34,3,2019-08-01,1,2,18,Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael",Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
34,35,3,2019-08-01,2,1,19,Team 1: Cockatoo,"Signor, Dominic","Jung, Tad",Team 4: Dolphin,"Signor, Sergio","Talolin, Nick","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
35,36,3,2019-08-01,2,2,20,Team 3: Dingo,"Kung, Bernard","Oldham, Cameron",Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
36,37,3,2019-08-01,2,3,21,Team 5: Dugong,"Dyer, Terry","Straughair, Thomas",Team 6: Echidna,"Goepfert, Paul","Holt, Ben","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
37,38,3,2019-08-01,3,1,1,Team 1: Emu,"Ryan, Paul","O'Regan, Brendan",Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
38,39,3,2019-08-01,3,2,2,Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael",Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
39,40,3,2019-08-01,3,3,3,Team 5: Galah,"Lee, Johnson","Howse, Kalan",Team 6: Goanna,"Mcerlain, Peter","Powell, John","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
40,41,3,2019-08-01,4,1,4,Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae",Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
41,42,3,2019-08-01,4,2,5,Team 3: Koala,"Smythe, David","Thomson, Jamie",Team 2: Kangaroo,"Goodwin, Jim","Hyde, David","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
42,43,3,2019-08-01,4,3,6,Team 5: Lizard,"Byrne, Jason","Ryan, Chris",Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
43,44,3,2019-08-01,5,1,11,Team 1: Magpie,"Emam, Arash","Salgueiro, Christian",Team 4: Possum,"Harrison, Peter","Mujica, Jose","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
44,45,3,2019-08-01,5,2,12,Team 3: Platypus,"Darlow, Anthony","Short, Craig",Team 2: Numbat,"Mazzaferri, Henry","Ballment, Meg","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
45,46,3,2019-08-01,5,3,13,Team 5: Quokka,"Timmermans,David","Symes, Brendon",Team 6: Quoll,"Van Veen, Peter","Rewell, Luke","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
46,47,3,2019-08-01,6,1,14,Team 1: Seal,"Wakefield, Paul","Nguyen, Khanh",Team 2: Sugar Glider,"Falconer, Colin","Winsemius, Karen","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
47,48,3,2019-08-01,6,2,15,Team 4: Turtle,"Florey, Linda","Dodson, Michelle",Team 3: Tasmanian Devil,"Powell, Robyn","Jordan, Julia","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
48,49,4,2019-08-08,1,1,20,Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh",Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
49,50,4,2019-08-08,1,2,21,Team 2: Bilby,"Keating, John","Collier, Mark",Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
50,51,4,2019-08-08,2,1,1,Team 3: Dingo,"Kung, Bernard","Oldham, Cameron",Team 1: Cockatoo,"Signor, Dominic","Jung, Tad","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
51,52,4,2019-08-08,2,2,2,Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth",Team 6: Echidna,"Goepfert, Paul","Holt, Ben","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
52,53,4,2019-08-08,2,3,3,Team 4: Dolphin,"Signor, Sergio","Talolin, Nick",Team 5: Dugong,"Dyer, Terry","Straughair, Thomas","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
53,54,4,2019-08-08,3,1,4,Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael",Team 1: Emu,"Ryan, Paul","O'Regan, Brendan","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
54,55,4,2019-08-08,3,2,5,Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando",Team 6: Goanna,"Mcerlain, Peter","Powell, John","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
55,56,4,2019-08-08,3,3,6,Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ",Team 5: Galah,"Lee, Johnson","Howse, Kalan","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
56,57,4,2019-08-08,4,1,11,Team 3: Koala,"Smythe, David","Thomson, Jamie",Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
57,58,4,2019-08-08,4,2,12,Team 2: Kangaroo,"Goodwin, Jim","Hyde, David",Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
58,59,4,2019-08-08,4,3,13,Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark",Team 5: Lizard,"Byrne, Jason","Ryan, Chris","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
59,60,4,2019-08-08,5,1,14,Team 3: Platypus,"Darlow, Anthony","Short, Craig",Team 1: Magpie,"Emam, Arash","Salgueiro, Christian","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
60,61,4,2019-08-08,5,2,15,Team 2: Numbat,"Mazzaferri, Henry","Ballment, Meg",Team 6: Quoll,"Van Veen, Peter","Rewell, Luke","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
61,62,4,2019-08-08,5,3,16,Team 4: Possum,"Harrison, Peter","Mujica, Jose",Team 5: Quokka,"Timmermans,David","Symes, Brendon","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
62,63,4,2019-08-08,6,1,17,Team 3: Tasmanian Devil,"Powell, Robyn","Jordan, Julia",Team 1: Seal,"Wakefield, Paul","Nguyen, Khanh","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
63,64,4,2019-08-08,6,2,18,Team 2: Sugar Glider,"Falconer, Colin","Winsemius, Karen",Team 4: Turtle,"Florey, Linda","Dodson, Michelle","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
64,65,5,2019-08-15,1,1,1,Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter",Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
65,66,5,2019-08-15,1,2,2,Team 2: Bilby,"Keating, John","Collier, Mark",Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
66,67,5,2019-08-15,2,1,3,Team 1: Cockatoo,"Signor, Dominic","Jung, Tad",Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
67,68,5,2019-08-15,2,2,4,Team 5: Dugong,"Dyer, Terry","Straughair, Thomas",Team 3: Dingo,"Kung, Bernard","Oldham, Cameron","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
68,69,5,2019-08-15,2,3,5,Team 6: Echidna,"Goepfert, Paul","Holt, Ben",Team 4: Dolphin,"Signor, Sergio","Talolin, Nick","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
69,70,5,2019-08-15,3,1,11,Team 1: Emu,"Ryan, Paul","O'Regan, Brendan",Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
70,71,5,2019-08-15,3,2,12,Team 5: Galah,"Lee, Johnson","Howse, Kalan",Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
71,72,5,2019-08-15,3,3,13,Team 6: Goanna,"Mcerlain, Peter","Powell, John",Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
72,73,5,2019-08-15,4,1,14,Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae",Team 2: Kangaroo,"Goodwin, Jim","Hyde, David","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
73,74,5,2019-08-15,4,2,15,Team 5: Lizard,"Byrne, Jason","Ryan, Chris",Team 3: Koala,"Smythe, David","Thomson, Jamie","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
74,75,5,2019-08-15,4,3,16,Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza",Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
75,76,5,2019-08-15,5,1,17,Team 1: Magpie,"Emam, Arash","Salgueiro, Christian",Team 2: Numbat,"Mazzaferri, Henry","Ballment, Meg","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
76,77,5,2019-08-15,5,2,18,Team 5: Quokka,"Timmermans,David","Symes, Brendon",Team 3: Platypus,"Darlow, Anthony","Short, Craig","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
77,78,5,2019-08-15,5,3,19,Team 6: Quoll,"Van Veen, Peter","Rewell, Luke",Team 4: Possum,"Harrison, Peter","Mujica, Jose","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
78,79,5,2019-08-15,6,1,20,Team 1: Seal,"Wakefield, Paul","Nguyen, Khanh",Team 4: Turtle,"Florey, Linda","Dodson, Michelle","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
79,80,5,2019-08-15,6,2,21,Team 2: Sugar Glider,"Falconer, Colin","Winsemius, Karen",Team 3: Tasmanian Devil,"Powell, Robyn","Jordan, Julia","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
80,81,6,2019-08-22,1,1,4,Team 2: Bilby,"Keating, John","Collier, Mark",Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
81,82,6,2019-08-22,1,2,5,Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh",Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
82,83,6,2019-08-22,2,1,11,Team 6: Echidna,"Goepfert, Paul","Holt, Ben",Team 1: Cockatoo,"Signor, Dominic","Jung, Tad","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
83,84,6,2019-08-22,2,2,12,Team 5: Dugong,"Dyer, Terry","Straughair, Thomas",Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
84,85,6,2019-08-22,2,3,13,Team 4: Dolphin,"Signor, Sergio","Talolin, Nick",Team 3: Dingo,"Kung, Bernard","Oldham, Cameron","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
85,86,6,2019-08-22,3,1,14,Team 6: Goanna,"Mcerlain, Peter","Powell, John",Team 1: Emu,"Ryan, Paul","O'Regan, Brendan","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
86,87,6,2019-08-22,3,2,15,Team 5: Galah,"Lee, Johnson","Howse, Kalan",Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
87,88,6,2019-08-22,3,3,16,Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ",Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
88,89,6,2019-08-22,4,1,17,Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza",Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
89,90,6,2019-08-22,4,2,18,Team 5: Lizard,"Byrne, Jason","Ryan, Chris",Team 2: Kangaroo,"Goodwin, Jim","Hyde, David","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
90,91,6,2019-08-22,4,3,19,Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark",Team 3: Koala,"Smythe, David","Thomson, Jamie","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
91,92,6,2019-08-22,5,1,20,Team 6: Quoll,"Van Veen, Peter","Rewell, Luke",Team 1: Magpie,"Emam, Arash","Salgueiro, Christian","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
92,93,6,2019-08-22,5,2,21,Team 5: Quokka,"Timmermans,David","Symes, Brendon",Team 2: Numbat,"Mazzaferri, Henry","Ballment, Meg","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
93,94,6,2019-08-22,5,3,1,Team 4: Possum,"Harrison, Peter","Mujica, Jose",Team 3: Platypus,"Darlow, Anthony","Short, Craig","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
94,95,6,2019-08-22,6,1,2,Team 2: Sugar Glider,"Falconer, Colin","Winsemius, Karen",Team 1: Seal,"Wakefield, Paul","Nguyen, Khanh","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
95,96,6,2019-08-22,6,2,3,Team 3: Tasmanian Devil,"Powell, Robyn","Jordan, Julia",Team 4: Turtle,"Florey, Linda","Dodson, Michelle","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
96,97,7,2019-08-29,1,1,11,Team 1: Bandicoot,"Bhiwarkar, Mangesh","Gubicak, Peter",Team 3: Brolga,"Pilz, Lothar","Harrison, Leigh","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
97,98,7,2019-08-29,1,2,12,Team 2: Bilby,"Keating, John","Collier, Mark",Team 4: Cassowary,"Harris, Lachlan","Weighell, Michael","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
98,99,7,2019-08-29,2,1,13,Team 1: Cockatoo,"Signor, Dominic","Jung, Tad",Team 5: Dugong,"Dyer, Terry","Straughair, Thomas","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
99,100,7,2019-08-29,2,2,14,Team 2: Crocodile,"Goodridge, Robert","Probyn-Smith, Garth",Team 4: Dolphin,"Signor, Sergio","Talolin, Nick","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
100,101,7,2019-08-29,2,3,15,Team 3: Dingo,"Kung, Bernard","Oldham, Cameron",Team 6: Echidna,"Goepfert, Paul","Holt, Ben","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
101,102,7,2019-08-29,3,1,16,Team 1: Emu,"Ryan, Paul","O'Regan, Brendan",Team 5: Galah,"Lee, Johnson","Howse, Kalan","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
102,103,7,2019-08-29,3,2,17,Team 2: Fairy Penguin,"Zeng, Jimmy","Salgueiro, Fernando",Team 4: Fur Seal,"Morgan, Shane","Mendes, Champ","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
103,104,7,2019-08-29,3,3,18,Team 3: Flying Fox,"Jefimenko, Paul","Mazzaferri, Michael",Team 6: Goanna,"Mcerlain, Peter","Powell, John","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
104,105,7,2019-08-29,4,1,19,Team 1: Ibis,"Zdimirovic, Zoltan","Harrison, Schae",Team 5: Lizard,"Byrne, Jason","Ryan, Chris","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
105,106,7,2019-08-29,4,2,20,Team 2: Kangaroo,"Goodwin, Jim","Hyde, David",Team 4: Kookaburra,"Blattman, Ben","Ponsonby, Mark","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
106,107,7,2019-08-29,4,3,21,Team 3: Koala,"Smythe, David","Thomson, Jamie",Team 6: Lyrebird,"Thompson, David","Shamakhy, Alireza","[[[], []], [[], []], [[], []], [[], []], [[], []]]"
107,108,7,2019-08-29,5,1,1,Team 1: Magpie,"Emam, Arash","Salgueiro, Christian",Team 5: Quokka,"Timmermans,David","Symes, Brendon","[[[], []], [[], []], [[], []], [[], []], [[], []]]"

END

# Generate team and player statistic dictionaries

# Go through the whole full_table_df line by line.

In [21]:
print('BEGIN')

team_rank,player_rank = reset_team_player_rank(diag, section_team_composition_df)Ã¥

full_table_df_shape = full_table_df.shape
#print( full_table_df.info(verbose=False) )
#print( full_table_df_shape )

for unique_match_no0 in range(full_table_df_shape[0]):
    #print('unique_match_no0=',unique_match_no0)
    
    section = full_table_df.loc[unique_match_no0,:]['Section']
    ROUND = full_table_df.loc[unique_match_no0,:]['Round']
    match = full_table_df.loc[unique_match_no0,:]['Match']
    
    #print('section,ROUND,match=',section,ROUND,match)
    
    override_result = None
    team_sheet_df, summary_df = match_team_summary(diag, full_table_df, section, ROUND, match, False, number_of_games_per_match, number_of_matches_per_match, override_result)
    
    if(type(team_sheet_df) == type(None) and type(summary_df) != type(None)):
        raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
    if(type(team_sheet_df) != type(None) and type(summary_df) == type(None)):
        raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))
        
    if(type(team_sheet_df) != type(None) and type(summary_df) != type(None)):
        print(CRED+'updating team/player ranking...'+CEND)
        team_rank = update_team_rank(diag, team_sheet_df, summary_df, number_of_games_per_match, number_of_matches_per_match)
        player_rank = update_player_rank(diag, team_sheet_df, number_of_games_per_match, number_of_matches_per_match)
#         print('team_rank=',team_rank)
#         print('player_rank=',player_rank)
        
    #print(team_sheet_df,summary_df)
    
if(diag): print('team_rank=',team_rank)
if(diag): print('player_rank=',player_rank)

#raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

print('END')

BEGIN
Team A/B wins over Team X/Y.
updating team/player ranking...
Team X/Y wins over Team A/B.
updating team/player ranking...
END

# print out section team and player rankings.

In [28]:
print('BEGIN')

#number_sections

for section0 in range(number_sections):
    team_table = {}
    section_stuff = section_team_composition_df.loc[section_team_composition_df['Section'] == section0+1].values
    
    for cnt in range(len(section_stuff)):
        team_name = section_stuff[cnt][2]
        #print(cnt,team_name)
        team_table[team_name] = team_rank[team_name]
    
    #print(section0+1,team_table)
    print_team_table(diag, team_table)
    
for section0 in range(number_sections):
    player_table = {}
    section_stuff = section_team_composition_df.loc[section_team_composition_df['Section'] == section0+1].values
    
    #print('section_stuff=',section_stuff)

    for cnt in range(len(section_stuff)):
        player_names = section_stuff[cnt][3:4+1]
        #print('player_names=',player_names)

        for player_name in player_names:
            player_table[player_name] = player_rank[player_name]

    #print(section0+1,player_table)
    print_player_table(diag, player_table)

#raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

print('END')

BEGIN

        Team  Section  Rounds  Won  Lost
3  Cassowary  1        1       41   0
0  Bandicoot  1        1       36   5
2  Brolga     1        1       5    36
1  Bilby      1        1       0    41

        Team  Section  Rounds  Won  Lost
0  Cockatoo   2        0       0    0
1  Crocodile  2        0       0    0
2  Dingo      2        0       0    0
3  Dolphin    2        0       0    0
4  Dugong     2        0       0    0
5  Echidna    2        0       0    0

            Team  Section  Rounds  Won  Lost
0  Emu            3        0       0    0
1  Fairy Penguin  3        0       0    0
2  Flying Fox     3        0       0    0
3  Fur Seal       3        0       0    0
4  Galah          3        0       0    0
5  Goanna         3        0       0    0

         Team  Section  Rounds  Won  Lost
0  Ibis        4        0       0    0
1  Kangaroo    4        0       0    0
2  Koala       4        0       0    0
3  Kookaburra  4        0       0    0
4  Lizard      4        0       0    0
5  Lyrebird    4        0       0    0

       Team  Section  Rounds  Won  Lost
0  Magpie    5        0       0    0
1  Numbat    5        0       0    0
2  Platypus  5        0       0    0
3  Possum    5        0       0    0
4  Quokka    5        0       0    0
5  Quoll     5        0       0    0

              Team  Section  Rounds  Won  Lost
0  Seal             6        0       0    0
1  Sugar Glider     6        0       0    0
2  Tasmanian Devil  6        0       0    0
3  Turtle           6        0       0    0

               Player  Section  Won  Lost  Total
6  Harris, Lachlan     1        14   0     14
7  Weighell, Michael   1        14   0     14
0  Bhiwarkar, Mangesh  1        12   2     14
1  Gubicak, Peter      1        12   2     14
4  Pilz, Lothar        1        2    12    14
5  Harrison, Leigh     1        2    12    14
2  Keating, John       1        0    14    14
3  Collier, Mark       1        0    14    14

                 Player  Section  Won  Lost  Total
0   Signor, Dominic      2        0    0     0
1   Jung, Tad            2        0    0     0
2   Goodridge, Robert    2        0    0     0
3   Probyn-Smith, Garth  2        0    0     0
4   Kung, Bernard        2        0    0     0
5   Oldham, Cameron      2        0    0     0
6   Signor, Sergio       2        0    0     0
7   Talolin, Nick        2        0    0     0
8   Dyer, Terry          2        0    0     0
9   Straughair, Thomas   2        0    0     0
10  Goepfert, Paul       2        0    0     0
11  Holt, Ben            2        0    0     0

                 Player  Section  Won  Lost  Total
0   Ryan, Paul           3        0    0     0
1   O'Regan, Brendan     3        0    0     0
2   Zeng, Jimmy          3        0    0     0
3   Salgueiro, Fernando  3        0    0     0
4   Jefimenko, Paul      3        0    0     0
5   Mazzaferri, Michael  3        0    0     0
6   Morgan, Shane        3        0    0     0
7   Mendes, Champ        3        0    0     0
8   Lee, Johnson         3        0    0     0
9   Howse, Kalan         3        0    0     0
10  Mcerlain, Peter      3        0    0     0
11  Powell, John         3        0    0     0

                Player  Section  Won  Lost  Total
0   Zdimirovic, Zoltan  4        0    0     0
1   Harrison, Schae     4        0    0     0
2   Goodwin, Jim        4        0    0     0
3   Hyde, David         4        0    0     0
4   Smythe, David       4        0    0     0
5   Thomson, Jamie      4        0    0     0
6   Blattman, Ben       4        0    0     0
7   Ponsonby, Mark      4        0    0     0
8   Byrne, Jason        4        0    0     0
9   Ryan, Chris         4        0    0     0
10  Thompson, David     4        0    0     0
11  Shamakhy, Alireza   4        0    0     0

                  Player  Section  Won  Lost  Total
0   Emam, Arash           5        0    0     0
1   Salgueiro, Christian  5        0    0     0
2   Mazzaferri, Henry     5        0    0     0
3   Ballment, Meg         5        0    0     0
4   Darlow, Anthony       5        0    0     0
5   Short, Craig          5        0    0     0
6   Harrison, Peter       5        0    0     0
7   Mujica, Jose          5        0    0     0
8   Timmermans,David      5        0    0     0
9   Symes, Brendon        5        0    0     0
10  Van Veen, Peter       5        0    0     0
11  Rewell, Luke          5        0    0     0

             Player  Section  Won  Lost  Total
0  Wakefield, Paul   6        0    0     0
1  Nguyen, Khanh     6        0    0     0
2  Falconer, Colin   6        0    0     0
3  Winsemius, Karen  6        0    0     0
4  Powell, Robyn     6        0    0     0
5  Jordan, Julia     6        0    0     0
6  Florey, Linda     6        0    0     0
7  Dodson, Michelle  6        0    0     0

END

# Validation/Maintenance of match sheets.

In [30]:
print('BEGIN')

################################################################################

#check if files exist in both directories, they should not.

################################################################################

input_raw_files = sorted(glob.glob(json_directory+'/section_??_round_??_match_??_data.json'))
for input_file in input_raw_files:
    file1 = json_directory+'/'+just_file_name(diag, input_file)
    file2 = validated_json_directory+'/'+just_file_name(diag, input_file)
    if(os.path.exists(file1) and os.path.exists(file2)):
       print(file1)
       print(file2)
       raise SystemExit('function case 1: file exists in both raw and validated directory.'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
################################################################################

input_validated_files = sorted(glob.glob(json_directory+'/section_??_round_??_match_??_data.json'))
for input_file in input_validated_files:
    file1 = json_directory+'/'+just_file_name(diag, input_file)
    file2 = validated_json_directory+'/'+just_file_name(diag, input_file)
    if(os.path.exists(file1) and os.path.exists(file2)):
       print(file1)
       print(file2)
       raise SystemExit('function case 2: file exists in both raw and validated directory.'+__file__+' line number: '+str(inspect.stack()[0][2]))
    
################################################################################

print(CRED+'Processing '+str(len(input_raw_files))+' files:'+CEND)

for cnt,input_file in enumerate(input_raw_files):
    
    input_json_file = just_file_name(diag, input_file)
    
    section, ROUND, match = section_ROUND_match_from_json_file(diag, json_directory+'/'+input_json_file)
    input_json_meta_file = 'section_'+'{0:02d}'.format(section)+'_round_'+'{0:02d}'.format(ROUND)+'_match_'+'{0:02d}'.format(match)+'_meta.json'

    print(CGREEN+str(cnt+1)+'/'+str(len(input_raw_files))+': Examining input_json_file='+input_json_file+CEND)
    print(CGREEN+str(cnt+1)+'/'+str(len(input_raw_files))+': Examining input_json_meta_file='+input_json_meta_file+CEND)
    
    if(not os.path.exists(json_directory+'/'+input_json_meta_file)):
        print(json_directory+'/'+input_json_meta_file)
        raise SystemExit('function: missing meta twin file.'+__file__+' line number: '+str(inspect.stack()[0][2]))

    json_match_df = pd.read_json(json_directory+'/'+input_json_file, orient=json_orient)
    
    results_teamA = chunk_them(diag, json_match_df['Results Team A'].values, 7)
    results_teamB = chunk_them(diag, json_match_df['Results Team B'].values, 7)
    
    if(len(results_teamA) != len(results_teamB)):
        raise SystemExit('function: len(results_teamA) != len(results_teamB).'+__file__+' line number: '+str(inspect.stack()[0][2]))

    if(diag): print('results_teamA=',results_teamA)

        #here we are always overriding result with that from input so that we can display it to make a decision
        #about whether it is correct or not.
        
    override_result = []
    for cnt,results in enumerate(results_teamA):
        override_result.append( [results_teamA[cnt], results_teamB[cnt] ])
        
    #print('override_result=',override_result)
        
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

#     display(json_match_df)
    
    if(diag): print('section, ROUND, match=', section, ROUND, match)
     
#     override_result = None
    
    #heiden
    
    team_sheet_df, summary_df = match_team_summary(diag, full_table_df, section, ROUND, match, True, number_of_games_per_match, number_of_matches_per_match, override_result)

    display(team_sheet_df)

    display(summary_df)
        
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

    for n in range(999):
        try:
            QUESTION = input(CRED+'Would you like to move this raw file to the validated area? [y/n] or 0=break'+CEND)
        except:
            print('Try again.')
            continue
            
        if(not QUESTION.isalpha() and int(QUESTION) == 0):
            raise SystemExit('function: Exiting Validation.'+__file__+' line number: '+str(inspect.stack()[0][2]))
        elif(QUESTION != 'y' and QUESTION != 'n'):
            print('Only "y" or "n", try again.')
            continue
        else:
            break

    if(QUESTION == 'y'):
        print(CGREEN+'Move '+json_directory+'/'+input_json_file+' to '+validated_json_directory+CEND)
        print(CGREEN+'Move '+json_directory+'/'+input_json_meta_file+' to '+validated_json_directory+CEND)
        
        #could check on value of newPath
        
        newPath = shutil.move(json_directory+'/'+input_json_file, validated_json_directory)
        print('newPath=',newPath)
        newPath = shutil.move(json_directory+'/'+input_json_meta_file, validated_json_directory)
        print('newPath=',newPath)
    else:
        print(CGREEN+'Not moving these raw file/meta files to validated directory.'+CEND)
    
    #raise SystemExit('STOP!:'+__file__+' line number: '+str(inspect.stack()[0][2]))

#input_json_file = 'section_'+'{0:02d}'.format(section0+1)+'_round_'+'{0:02d}'.format(round0+1)+'_match_'+'{0:02d}'.format(match0+1)+'_data.json'

# if(os.path.exists(json_directory+'/'+input_json_file)):
#     print(CRED+json_directory+'/'+input_json_file+' exists...loading'+CEND)
#     json_match_df = pd.read_json(r''+json_directory+'/'+input_json_file, orient=json_orient)
    
print('END')

BEGIN
Processing 0 files:
END

# Live data entering.

In [ ]:
print('BEGIN')

for n0 in range(999):
    print('Iteration [0] '+str(n0+1))
    live_match(diag, full_table_df, number_of_games_per_match, number_of_matches_per_match, json_directory)
    
print('END')

# END OF IMPORANT STUFF

In [10]:
for round0 in range(10):
    print(round0,round0%3)

0 0
1 1
2 2
3 0
4 1
5 2
6 0
7 1
8 2
9 0